### ISSUE TITLE
JSONRPC Not Reading in Parameters

### ISSUE THREAD

**Issue by adambanker** [paws-r/paws#16]
When running in the following code:
```
library(paws.batch)
(a <- describe_compute_environments(maxResults = 3))
```

I noticed that the parameters were not being used. The http request body is being created properly in the file handlers_jsonrpc.R.

However, the body is not being set at line 14 of that same file because `request$client_info$target_prefix` is null.

**Comment by davidkretch** [comment]
Addressed by #18
