### ISSUE TITLE
Paws package unable to get IAM credentials from an EC2 Instance profile

### ISSUE THREAD

**Issue by Naveen-Annam-CMA** [paws-r/paws#169]
**Issue**

I'm trying to use paws package on an EC2 instance but it fails to get IAM credentials from the instance profile and i need to explicitly set the values for 'AWS_ACCESS_KEY_ID' and 'AWS_SECRET_ACCESS_KEY' in the environment. I get the following error when i try to get account summary on the instance or use any of the AWS services in the paws package with an IAM instance profile.

Below is the error message given for when i try to get account summary on an EC2 Instance

> Error: Argument 'txt' must be a JSON string, URL or file.
Traceback:
>1. temp$get_account_summary()
>2. send_request(request)
>3. sign(request)
>4. run(request, sign)
>5. handler$fn(request)
>6. sign_sdk_request_with_curr_time(request)
>7. sign_with_body(v4, request$http_request, request$body, name, 
 .     region, request$expire_time, request$expire_time > 0, signing_time)
>8. get_credentials(signer$credentials)
>9. provider()
>10. get_iam_role()
>11. jsonlite::fromJSON(iam_role_response$body)
>12. stop("Argument 'txt' must be a JSON string, URL or file.")
>13. base::stop(..., call. = FALSE)

iam_role_response is NULL which is why the error is given. If i do a simple GET request on the instance to  the metadata url "http://169.254.169.254/....", i can successfully retrieve the security credentials which is where PAWS seems to be failing. 

**Steps to reproduce**
Using R version 3.5.1, with latest PAWS package running on EC2 Instance

1. Paste the following code

```
Sys.setenv(
  AWS_REGION = "eu-west-2"
)
```
```
iaminfo <- paws::iam()
iaminfo$get_account_summary()
```

2. Run the code and wait a few seconds for the error message to appear.

**Comment by davidkretch** [comment]
Sorry about that.  Thank you for the bug report.  I'll take a look later today.

**Comment by davidkretch** [comment]
I've made a fix.  We'll update the version on CRAN, which will probably be available in a couple days.  This functionality is provided in the `paws.common` package, which is what you'll eventually need to update.

If you want to try installing the latest paws.common package from GitHub, you can get it with:

```
remotes::install_github("paws-r/paws", subdir = "paws.common")
```

**Comment by davidkretch** [comment]
The newest `paws.common` with the fix for EC2 IAM role credentials is now on CRAN.  Let us know whether it works for you.

**Comment by Naveen-Annam-CMA** [comment]
There seems to be a new error. It fails at provider(). Before it seems to go past 'get_iam_role()'
>Error in provider(): No credentials provided
>Traceback:
>
>1. iaminfo$get_account_summary()
>2. send_request(request)
>3. sign(request)
>4. run(request, sign)
>5. handler$fn(request)
>6. sign_sdk_request_with_curr_time(request)
>7. sign_with_body(v4, request$http_request, request$body, name, 
 .     region, request$expire_time, request$expire_time > 0, signing_time)
>8. get_credentials(signer$credentials)
>9. provider()
>10. stop("No credentials provided")

**Comment by davidkretch** [comment]
Hmmm, nuts.  Can you try running

```
paws.common:::get_iam_role()
```

**Comment by Naveen-Annam-CMA** [comment]
That seems to work. Hmmm not sure. Just like before i can't access any of the AWS services.

**Comment by davidkretch** [comment]
I'm not sure either.  Could you also try `paws.common:::iam_credentials_provider()`.  It returns access key, secret key, and token, or null if it can't find it.  I've got to run but will look again later.  Sorry for the issues.

**Comment by Naveen-Annam-CMA** [comment]
It returns NULL. I had a look at the code and got `paws.common:::iam_credentials_provider()` to work by changing get_iam_role() function.  The change was from get_instance_metadata("iam/info") to get_instance_metadata("iam/security-credentials") and returning the body which is just the role-name. 

`iam/security-credentials/role-name`
```
# Get the name of the IAM Role from the instance meta-data
get_iam_role <- function() {

  iam_role_response <-  get_instance_metadata("iam/security-credentials")

  if (is.null(iam_role_response)) return(NULL)

  iam_role_name <- rawToChar(iam_role_response$body)

  return(iam_role_name)
}
```

AWS documentation had the following info 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html

> Retrieving Security Credentials from Instance Metadata
> An application on the instance retrieves the security credentials provided by the role from the instance metadata item iam/security-credentials/role-name. The application is granted the permissions for the actions and resources that you've defined for the role through the security credentials associated with the role. These security credentials are temporary and we rotate them automatically. We make new credentials available at least five minutes before the expiration of the old credentials.

**Comment by davidkretch** [comment]
Thanks, that also works for us -- I will add it to the code shortly.

There is a larger issue with how we deal with regions for services like IAM that we'll fix soon.  For example, I wasn't able to get `get_account_summary` to work in eu-west-2 because the API request should be signed with region us-east-1.

**Comment by Naveen-Annam-CMA** [comment]
Great thank you. I will close this issue.

**Comment by glmourad** [comment]
Hi, 

I'm also getting NULL when invoking paws.common:::iam_credentials_provider().
I was wondering if this could happen due IMDS metadata version of the EC2 instance.

Using the latest version.

Thanks

**Comment by davidkretch** [comment]
Yeah, you are right, if you are using IMDSv2, Paws currently doesn't support that so it won't work at all.  I can't tell you when it will be available unfortunately.  Neither of us two maintainers have time to work on it.  If you or any of your colleagues would like to work on it I would be happy to answer questions though.

**Comment by DyfanJones** [comment]
Hi @nate9336 this is related to https://github.com/paws-r/paws/issues/948. Due the to move to httr2 headers have become more strict. 

```r
install.packages('paws.common', repos = c('https://paws-r.r-universe.dev', 'https://cloud.r-project.org'))
```

We have a fixed this in dev. I will need to run some revdeps check to ensure no dependent package is affected with the latest changes to paws.common when releasing to the cran

**Comment by nate9336** [comment]
Awesome - thank you!
