### ISSUE TITLE
authentication with temporary security credentials

### ISSUE THREAD

**Issue by madhyastha** [paws-r/paws#185]
Hi,
 It seems that I can authenticate with normal AWS credentials but not with a temporary security credentials - is this correct and would it be possible to add support for this?

**Comment by adambanker** [comment]
You are correct that we do not currently support authentication with temporary security credentials. You can find currently supported authentication methods here: [Supported Credentials](https://github.com/paws-r/paws/blob/master/docs/credentials.md).

I agree that it would be a good idea to add support for temporary security credentials so we will put it high on our to-do list.

Thanks for submitting the issue!

**Comment by madhyastha** [comment]
I verified that simply checking for the token and passing it along in the
creds structure in credential_providers.R works, if that helps!

Could you email me directly at taramad@amazon.com to discuss some things
offline?

**Comment by davidkretch** [comment]
Hello @madhyastha.  I am really sorry for the long wait.  We've added support for session tokens set in environment variable AWS_SESSION_TOKEN.  You'll have to install the latest version of `paws.common` which is now on CRAN.  Please let us know if this works for you.

Thank you!

**Comment by davidkretch** [comment]
Addressed in the environment variable case by #191.
