### ISSUE TITLE
Passing credentials using config=list()

### ISSUE THREAD

**Issue by mswerlick** [paws-r/paws#210]
Unsure whether this is an issue on my end or a bug (my guess is the former. I installed `paws` using `install.packages`). Based on [this](https://github.com/paws-r/paws/blob/master/docs/credentials.md#setting-credentials-with-custom-service-config) I'd expect the below to create an s3 service with the credentials provided:

```r
credentials <- ini::read.ini('~/.aws/credentials')

s3 <- paws::s3(
     config = list(
         credentials = list(
             creds = list(
                 access_key_id = credentials$default$aws_access_key_id,
                 secret_access_key = credentials$default$aws_secret_access_key,
                 session_token = credentials$default$aws_session_token
             )
         )
     )
 )
```

Instead I get this error
```
Error in paws::s3(config = list(credentials = list(creds = list(access_key_id = credentials$default$aws_access_key_id,  : 
  unused argument (config = list(credentials = list(creds = list(access_key_id = credentials$default$aws_access_key_id, secret_access_key = credentials$default$aws_secret_access_key, session_token = credentials$default$aws_session_token))))
```

Session Info
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] paws_0.1.4

loaded via a namespace (and not attached):
[1] compiler_3.6.1               ini_0.3.1                    tools_3.6.1                  paws.security.identity_0.1.4
[5] paws.common_0.2.3            rlang_0.4.0.9005             paws.management_0.1.4       
```
My creds file looks like
```
[default]
aws_access_key_id = XXXXXXXX
aws_secret_access_key =XXXXXXXXXXXXXXX
aws_session_token = XXXXXXXX
aws_session_expiration = XXXXXXXX
aws_security_token = XXXXXXXXXX
```

I am able to get methods 2,3, and 5 from the [credentials doc](https://github.com/paws-r/paws/blob/master/docs/credentials.md#setting-credentials-with-custom-service-config), but need access to multiple accounts which I was hoping the above would let me do (either via profiles or assuming roles with `sts`). Any insight on how to get this working would be really appreciated.

**Comment by davidkretch** [comment]
Sorry about that.  We just added that and it's not on CRAN yet.  We hope to get it on CRAN in the next few days.  We will add a note to this issue when it's available.

**Comment by mswerlick** [comment]
Perfect, thanks for the quick response. This package looks amazing and I'm really looking forward to using it

**Comment by davidkretch** [comment]
Hello @mswerlick and @DyfanJones, the newest version of paws is now on CRAN, with support for setting credentials etc. in the `config` parameter.  Please let us know if you run into any issues.  Sorry for the wait and thank you!

**Comment by mswerlick** [comment]
@davidkretch tried this out and everything works. This is great, thank you!
