### ISSUE TITLE
Accessing the RDS Signer generator

### ISSUE THREAD

**Issue by davidski** [paws-r/paws#224]
Thanks a bunch for creating this package! It's fascinating seeing how the JS SDK has been used to generate all the functions here.

I'm looking to gain access to RDS's ability to authenticate database connections via IAM  (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.html). That seems exposed in the JavaScript SDK via a Signer generator under the RDS class (https://docs.amazonaws.cn/AWSJavaScriptSDK/latest/AWS/RDS/Signer.html). I'm unable to find any similar functions under the rds or the rdsdataservices portions of PAWS and I'm not familiar enough with the build system to trace back how those would get picked up.

Are these functions available or something that could be made available?

**Comment by davidkretch** [comment]
Thanks, we haven't tried using this before, but we'll work on it soon.  It looks like it requires a little bit of special handling unlike the rest of the RDS API operations, but I think it may be relatively straightforward.  We are also planning on better documenting the build system so it'll be easier to contribute -- sorry about that.

**Comment by davidkretch** [comment]
Hello again.  I'm sorry for the delay.  We have a branch where we've added this functionality.  Would you be willing to test it and let us know if it works for you, and whether the interface is satisfactory?

You can get it from the `feature/rds_auth_token` branch, e.g. `devtools::install_github("paws-r/paws/paws.common@feature/rds_auth_token")`.

Example code, which uses the paws.common package for implementation-specific reasons:

```
host <- "database-1.cluster-abcdef123456.us-east-1.rds.amazonaws.com"
port <- 3306
user <- "jane_doe"

build_auth_token <- paws.common:::rds_build_auth_token
token <- build_auth_token(
  endpoint = sprintf("%s:%s", host, port),
  region = "us-east-1",
  user = user
)
```

In the full release of Paws, you'd invoke it like the following.  It also has an optional `creds` parameter.

```
rds <- paws::rds()
token <- rds$build_auth_token("host:port", "us-east-1", "jane_doe")
```

**Comment by davidkretch** [comment]
The latest version of Paws on CRAN (0.1.6) now has this feature, which you can access with:

```
rds <- paws::rds()
token <- rds$build_auth_token("host:port", "us-east-1", "jane_doe")
```

Sorry again for the delay.  Please let us know if you have any issues.

**Comment by davidski** [comment]
Sorry I haven't been able to test this out. Thanks a bunch for implementing this! Looking forward to getting some time to pick this up again in the near future!

**Comment by davidkretch** [comment]
Sounds good, thank you!  Let us know if you have any issues!
