### ISSUE TITLE
s3 methods fail ungracefully for bucket names that contain periods

### ISSUE THREAD

**Issue by tomsing1** [paws-r/paws#236]
It seems that the `s3` methods fail ungracefully when a bucket name that contains periods is passed:

```
s3$list_objects(Bucket = 'my.bucket.name.has.periods')
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL: no alternative certificate subject name matches target host name 'my.bucket.name.has.periods.s3.amazonaws.com'
```

There is some background on this error (which I don't fully understand) [on this page](https://www.s3express.com/kb/item39.htm).

In the past, I have used the [aws.s3](https://github.com/cloudyr/aws.s3) R package to access buckets with periods in their name, and it worked - so it seems that the is a workaround? Any suggestion would be greatly appreciated, as I have to work with existing buckets that cannot be renamed.

Many thanks!

**Comment by davidkretch** [comment]
Ha, that is an interesting bug.  We'll look into it.  Thanks.

**Comment by davidkretch** [comment]
There's now a fix on GitHub which you can get with `devtools::install_github("paws-r/paws/paws.common")`.  However due to CRAN submission frequency rules, we won't be able to upload a new version to CRAN for a few weeks.

**Comment by tomsing1** [comment]
Awesome - thanks a ton for fixing this so quickly. Now I can access the buckets that caused trouble before 🎉
