### ISSUE TITLE
Does not support S3 key names with spaces

### ISSUE THREAD

**Issue by davidkretch** [paws-r/paws#243]
The following fails with error `Error: HttpVersionNotSupported: The HTTP version specified is not supported.`.

```
s3$put_object(
  Body = s3_example,
  Bucket = bucket_name,
  Key = "a name with spaces"
)
```

**Comment by franksmithxyz** [comment]
I have noticed the same issue for s3$get_object.  Is there a hackaround for this?

**Comment by davidkretch** [comment]
Hmm... I will see if I can figure it out in the next couple days.

**Comment by davidkretch** [comment]
Hello! There is a bug fix in master but not yet on CRAN. It will be a few weeks before it is on CRAN due to rules about how often we can update a package. You can try the bug fix with `remotes::install_github("paws-r/paws/paws.common")`.

**Comment by davidkretch** [comment]
Hey, sorry for the delay! The bug fix is now on CRAN. You can get it by installing the latest `paws.common`. Let us know if you have issues. Thank you!
