### ISSUE TITLE
Question: Access http status codes/messages from requests?

### ISSUE THREAD

**Issue by ryanb8** [paws-r/paws#245]
Hi Team Paws,

Is there a way to view http status codes or http status messages from requests? 

I've played around with a few examples (listing object in s3, etc.), but I'm not seeing this data in the resulting payload or in the attributes. 

I've been poking around the source code looking for where http codes are interpreted, but there's a lot of meta-programming going on that I'm still working on wrapping my head around.😅 

I can also understand if this is out-of-scope for this project.

**Comment by davidkretch** [comment]
I think we want to keep function outputs to match what the AWS APIs define the outputs to look like, so I don't think we can include extra stuff in that output.  What we could work on is giving better error messages -- I think there is room for improvement there.  Let us know if that would help here.  We can also take a look at what the other SDKs give.

If the HTTP response status code is an error code (currently, 0 or >= 300), it will always raise an error in R.  The [`send_request`](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/request.R#L152) function checks for errors based on HTTP status codes using [`validate_response_handler`](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/handlers_core.R#L120), and then raises if there is one.  It creates an error message based on whatever it got back from AWS, and that depends on each service and potentially each operation, but we currently only report a minimal amount.

**Comment by ryanb8** [comment]
First, y'all are great to interact with - I really love this project and appreciate the obvious amount of effort that went into. I really have enjoyed poking around in the source code and learning about how y'all are making this thing work.

Let me explain what I'm trying to do and ask a few questions.

My end goal is to be able to auto-retry for 50* errors (server side). For example, my code had this error the other day: `Timeout was reached: [sts.amazonaws.com] Connection timed out after 10001 milliseconds`. (I think this is a 504.) I want to tell my code to sleep for a second and retry, because this fault was no fault of mine. I can get at this end goal by parsing error logs and retrying based on string matching, but it sounds nice to be able to just know what the code was. Do y'all have any ideas on how to do this cleanly?

I *think* giving better error messages would help. I have two ideas that could be combined if desired (or ignored entirely):

1. Encode httpstatus codes and messages as attributes on the error object itself:
    ```R
    s3_client <- paws::s3()
    resp <- tryCatch(s3_client$list_objects_v2(Bucket = "this_is_not_a_bucket_salfsjaflk", MaxKeys = 2), error = function(e) e)
    # some magic happens in paws.common where `attr(resp, "httpStatusCode") <- 404` is run or the error is a sub-class or something, then: 

    attributes(resp)
    # Output:
    ##$names
    ##[1] "message" "call"   
    ##
    ##$class
    ##[1] "simpleError" "error"       "condition"  
    ##
    ##$httpStatusCode
    ##[1] 404

   ```
2. Add error codes to error messages. This makes them easy to extract with string parsing tools.
    ```R
    s3_client <- paws::s3()
    resp <- tryCatch(s3_client$list_objects_v2(Bucket = "this_is_not_a_bucket_salfsjaflk", MaxKeys = 2), error = function(e) e)
    resp$message

    # Output:
    # "httpStatusCode:404 : NoSuchBucket: The specified bucket does not exist"
    # instead of 
    # "NoSuchBucket: The specified bucket does not exist"
    ```

**Comment by ryanb8** [comment]
I've spent sometime playing around in the code base trying to figure out how I would do either of these. I'm pretty convinced it would be within the `format_error` function (paws.common/R/error.R), but I haven't quite figured out where the functions that are actually stored in the handler list come from and what they are. I THINK the error object entering the `format_error` function isn't a traditional R error and likely has the `httpStatusCode` property, but that's just a gut/hunch.

**Comment by davidkretch** [comment]
Thank you!  We really like seeing people use it.  I definitely think your use case is one Paws should make straightforward to do, and I think we can and should try both of your suggestions.  If you work on it, we'd be happy to accept a pull request.  If not, we'll at least start on it within the next week.

For reference, the flow of an error looks like:
1. We get an HTTP response with a status code and however they report errors, which varies by service.  Both of these get stored in the `http_response` element (described [here](https://github.com/paws-r/paws/blob/c15690fdd0823ee5e07d26886f052600cbc54084/paws.common/R/net.R#L30)) of the Paws `request` object; the status code would be in `request$http_response$status_code`.  

     For example, S3 will report errors as XML in the body of the response, e.g. `"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>bucket-i-dont-own</BucketName><RequestId>123456</RequestId><HostId>abcdef</HostId></Error>"`.  

2. When there's an error, it calls the unmarshal error handler to get the error from the response.  This is defined per service; S3 uses 'REST-XML' and so it calls [`restxml_unmarshal_error`](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/handlers_restxml.R#L31) which in turn calls [`query_unmarshal_error`](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/handlers_query.R#L40) and finally [`xml_unmarshal_error`](https://github.com/paws-r/paws/blob/e37d003dd8b661408f02cb98bc318a2fbc3357e3/paws.common/R/xmlutil.R#L168).  These functions take the Paws `request` object, translate the XML into an R object that looks like an an [`Error`](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/error.R#L2), and puts it into `request$error`.  I think the unmarshal error handlers and the error objects are where we might also include the status code.

3. It calls `format_error` on the `request$error` object.

**Comment by ryanb8** [comment]
Ok, thanks so much for the explanation!

I'm interested in attempting a PR, but I'm not sure how quickly I'll be able to get it complete (due to work requirements + still learning) and I'm unsure if it will be of sufficient quality. 

It sounds like the path to a PR is:
1. Update the [Error structure](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/error.R#L2) to support more fields, mainly http status code. 
2. Update the [format_error function](https://github.com/paws-r/paws/blob/03c485ecda8bcd562eed82b91a57d8f967ba7475/paws.common/R/error.R#L9) to set httpstatus code as an attribute and format the error message appropriately.
3. For each protocol (i.e. each handlers_*****.R file), ensure that the `*****_unmarshall_error` function actually finds and extracts the httpStatusCode, and passes it correctly to the Error structure-function.
4. Make tests - I'm not 100% sure what this looks like. Some of the `tests_handlers_****` looks to have tests that look at unmarshalling errors, but not all do. I imagine it would be adding unmarshalling_error tests to those that don't have this functionality, and adding tests for the off chance that a status_code isn't there?

Does that seem like the right plan of attack?

**Comment by davidkretch** [comment]
That all sounds right on to me.  If you do have the time, we'd love to get your help.  We're working on a couple other things, and Adam, the other maintainer, is pretty busy with outside obligations; but I at least would like to see this implemented.  Also, feel free to email me at david.kretch@gmail.com.

**Comment by ryanb8** [comment]
#246  fixed this!
