### ISSUE TITLE
transfering files from one ec2 to another ec2 in same region

### ISSUE THREAD

**Issue by yonicd** [paws-r/paws#251]
Is it possible with paws to transfer files from one ec2 to another ec2 in same region? if so what methods would I use in the ec2 R6 object?

thanks

**Comment by davidkretch** [comment]
Unfortunately as far as I know that's not possible using only the EC2 API.  An alternative is:
1. Upload files from one instance to S3, download files from another instance using the S3 API.  We have an example of this in [examples/s3.R](https://github.com/paws-r/paws/blob/master/examples/s3.R) however it is not streamlined at all right now.  There's also a 5 GB limit for single-file uploads/downloads, after which it gets a lot more complex.

I can think of some other alternatives that require more setup (e.g. database, network file system) but I don't think know enough about the use case.  These alternatives wouldn't rely on Paws or the AWS APIs though.

**Comment by yonicd** [comment]
I was using the S3 bridge, but thought maybe this will give me a new more direct transfer. Thanks for the advice!

**Comment by davidkretch** [comment]
No problem, sorry about that!  Let us know if there are anything else comes up.  Also, would it be ok with you if I close the issue?

**Comment by yonicd** [comment]
sure
