### ISSUE TITLE
Support for Assume Role Provider

### ISSUE THREAD

**Issue by davidski** [paws-r/paws#253]
It would be wonderful if `paws` could support the Assume Role Provider functionality present in boto3/botocore and documented at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html. Specifically, I'm looking to find support for `paws` to read and honor the `source_profile`, `mfa_serial`,  and `credential_process` parameters. With these three, paws could be used to transparently assume a role where credentials are not stored on disk in plaintext, but instead are retrieved via secure storage with a  program such as [aws-vault](https://github.com/99designs/aws-vault), assuming a role with temporary credentials.

This is a complicated request, but is currently a missing feature in all of the R AWS packages and would be a tremendous add.

**Comment by davidkretch** [comment]
Thanks, yes, we'll try to work on that soon.  We started on part of it a while back actually.  I can't say when it'll be done though.

**Comment by dpastoor** [comment]
For those of you that stumble onto this, this was the workaround I came up with as a workaround:

```
get_creds_assumed_profile <- function(.x) {
  .profile_details <- ini::read.ini("~/.aws/credentials")[[.x]]
  if (is.null(.profile_details)) {
    stop(sprintf("no profile with the name `%s` found in ~/.aws/credentials file", .x))
  }
  profile <- .profile_details$source_profile
  # if no source_profile lets look for a credential_source, which will probably
  # be something like Ec2InstanceMetadata
  if (is.null(profile)) {
    profile <- .profile_details$credential_source
  }
  if (is.null(profile)) {
    stop("could not find either a credential_source or source_profile, please make sure one is set!")
  }
  sts <-paws::sts(config = list(credentials = 
                                  list(profile = profile), 
                                region = "us-east-1"))
  .pc <- sts$assume_role(.profile_details$role_arn, "assumed-role")
  return(list(
    access_key_id = .pc$Credentials$AccessKeyId,
    secret_access_key = .pc$Credentials$SecretAccessKey,
    session_token = .pc$Credentials$SessionToken
  ))
}
```

```
creds <-  get_creds_assumed_profile("techopsdev")
svc <- sts(config = list(credentials = list(creds = creds)))
svc$get_caller_identity() 
s3_svc <- s3(config = list(credentials = list(creds = creds)))
s3_svc$list_buckets()
```

From a quick look at the PR, this seems to be the direction the PR is going, just only had ~ 1 hr to come up with something for my team to mess with.

Under this script, you can use either source profiles or credential sources in ~/.aws/credentials and it will behave.

```
[techopsdev]
role_arn = arn:aws:iam::<account>:role/OrganizationAccountAccessRole
source_profile = MetrumRGCloudAdminSSO
```

or

```
[techopsdev]
role_arn = arn:aws:iam::<account>:role/S3accessPOC 
credential_source = Ec2InstanceMetadata
```

**Comment by davidkretch** [comment]
Hello, I am sorry for the long delay on this. There is a branch that supports `credential_source` and `source_profile` in the AWS shared config file. Would either one of you be willing to try it out? If so, you can get the branch with:

```r
devtools::install_github("paws-r/paws/paws.common@feature/assume_role")
```

Unfortunately supporting MFA and `mfa_serial` is going to take longer since it will require larger changes.

**Comment by davidkretch** [comment]
Hello again -- support for `credential_process` and for `role_arn` with `credential_source` and `source_profile` are now the CRAN `paws.common` package (version 0.3.5).

Thanks and be safe :-)

**Comment by davidkretch** [comment]
Support for MFA using `mfa_serial` in the config file is now in `main`. Specifically this supports MFA in concert with `role_arn` and either `credential_source` or `source_profile`.

It'll be a couple weeks before it is on CRAN due to update frequency rules.

**Comment by davidkretch** [comment]
Hello, support for MFA through `mfa_serial` is now on CRAN with `paws.common` version 0.3.9. Please let us know if you run into any issues. Sorry for the wait and thanks!
