### ISSUE TITLE
Error in interface[[1]] : subscript out of bounds on empty response

### ISSUE THREAD

**Issue by jrdi** [paws-r/paws#271]
I'm running a `put_metric_data` and getting the following `Error in interface[[1]] : subscript out of bounds`. Since CloudWatch is showing the data I have been debugging the response parsing.

I've found that in `xml_unmarshal` the first node is retrieved despite the name of the field and it happens to be the metadata when the API returns an empty response.

```r
# Unmarshal `data` provided as a list into the shape in `interface`.
xml_unmarshal <- function(data, interface, result_name = NULL) {
  root <- data[[1]]
  if (!is.null(result_name) && result_name %in% names(root)) {
    root <- root[[result_name]]
  }
  result <- xml_parse(root, interface)
  return(result)
}
```

![image](https://user-images.githubusercontent.com/67608/78565850-bd63ae80-781e-11ea-884c-e7c3cf350978.png)

Then when `xml_parse` is called (and then `xml_parse_list`) the node contains data but the interface object is requiring an empty list. Here you have the actual line that is crashing.

```r
xml_parse_list <- function(node, interface) {
  if (length(node) == 0) return(list())
  names(node) <- NULL
  result <- lapply(node, function(x) xml_parse(x, interface[[1]]))       <-----
  if (type(interface[[1]]) == "scalar") {
    result <- unlist(result)
  }
  return(result)
}
```

Shouldn't `xml_unmarshal` skip metadata node before extracting the first node by default?

**Comment by davidkretch** [comment]
Sorry about that but thank you for the bug report!  We'll try to fix this very soon.  Do you also have an example call to `put_metric_data` that we could try?

**Comment by jrdi** [comment]
Hey @davidkretch, thank you for your reply. Sure, here you have the exact snippet I'm using. Let me know if you need something else to reproduce it or if you prefer I can try to submit a PR with the patch.

```r
cloudwatch <- paws::cloudwatch()
cloudwatch$put_metric_data(Namespace = "Test.Namespace", list(
  list(
    MetricName = "Metric1",
    Value = 10,
    Unit = "Count"
  ),
  list(
    MetricName = "Metric2",
    Value = 20,
    Unit = "Count"
  )
))
```

**Comment by davidkretch** [comment]
Thanks!  It looks like we should not be calling the unmarshal handler at all in this case since the interface (i.e. the API response shape) is empty.  Sorry -- I put together a small fix.  I'll update this issue when a fix is available in master.

**Comment by davidkretch** [comment]
Hello, the fix is now available on GitHub, and plan to be on CRAN in a couple weeks.  You can get it from GitHub with `devtools::install_github("paws-r/paws/paws.common")`.

This no longer fails, but it doesn't give you any output.  I believe this is consistent with the other AWS SDKs but I may be mistaken.  Also, I ran into another bug putting in dates (#274) which I hope to have a fix for soon as well.

**Comment by jrdi** [comment]
@davidkretch thank you so much!
