### ISSUE TITLE
put Plotly HTML in S3 bucket

### ISSUE THREAD

**Issue by jbixon13** [paws-r/paws#291]
Thank you for your work on this package!

I have a use case where I'd like to programmatically upload the `HTML` from `htmlwidgets::saveWidget()` for a Plotly object in a Plumber API. I am currently able to successfully put the underlying data that is used in the plot as a `JSON` file in a bucket without issue as I don't have to write it out to storage, I can just run toJSON() on my data and upload as-is. This is done here: 

```r
#* Return JSON object - plot 1
#* @json 
#* @get /plot1
function() {
  # ridership
  transit_ridership <- transit %>% 
    filter(indicator_name == 'Total Ridership - Subways') %>% 
    mutate(monthly_actual = round((monthly_actual))) %>% 
    toJSON()
  
  # write json object to S3 storage
  s3$put_object(
    Body = transit_ridership,
    Bucket = 'bucket-name',
    Key = 'folder-name/plot1.json'
  )
}
``` 

I'm looking for a comparable solution with Plotly charts, is this possible or am I going about this the wrong way?

**Comment by adambanker** [comment]
Hi,

If you are looking for how you can upload the plot to s3 you can do the following.
First, you can use `htmlwidgets::saveWidget()` to save the widget to an html file.
Next, you can follow the example [here](https://github.com/paws-r/paws/blob/master/examples/s3.R) to upload the file to s3.

It should look something like:

```
file_name <- "example.html"
bucket_name <- "my_bucket"
key <- "example.html"

# Save plotly widget to html file where widget refers to a plotly widget you created
htmlwidgets::saveWidget(widget, file_name)

# Load the file as a raw binary
read_file <- file(file_name, "rb")
s3_example <- readBin(read_file, "raw", n = file.size(file_name))

# Upload file to s3
s3 <- paws::s3()
s3$put_object(
  Body = s3_example,
  Bucket = bucket_name,
  Key = file_name
)
```

**Comment by jbixon13** [comment]
I get the following when replicating your example: 
```r
Error in s3$put_object : object of type 'closure' is not subsettable
```

> It might also make sense for you to move all of your code - the data cleaning and plotting code - into an RMarkdown document that generates an html file

I don't think this is a viable option for me as I'm attempting to embed these plots in a React application through iframes (feel free to correct me if you think this is still an approach that makes sense).

**Comment by adambanker** [comment]
It looks like you left out the line where you define the s3 service object.
```
s3 <- paws::s3()
```
Also, I agree that my RMarkdown suggestion doesn't sound like a good fit here.

**Comment by jbixon13** [comment]
Thank you! I have that line defined earlier in my script but must have cleared it from my environment. 

It's correctly being put in the S3 bucket, but interestingly when I include it in my iframe it doesn't show up on the page as expected, it prompts me to download the file. This doesn't appear to be a frontend issue since I manually uploaded another html file and can render that successfully. 

This may be out of scope but I'm curious if you think uploading it as a binary file has anything to do with that. When I click on the file itself in S3 it opens downloads, opens in my browser, and renders with the expected chart. The html contents seem intact as well upon looking at them in a text editor.

**Comment by adambanker** [comment]
Good point. When you upload the file, you will need to set the content type to "text/html"
```
s3$put_object(
    Body = s3_example,
    Bucket = bucket_name,
    Key = 'MTA-article/plotly_test.html',
    ContentType="text/html"
)
```

**Comment by jbixon13** [comment]
that worked, thank you!

**Comment by adambanker** [comment]
Awesome! Glad to hear it
