### ISSUE TITLE
Signature 4 Authentication for API Gateway

### ISSUE THREAD

**Issue by wpenglish** [paws-r/paws#301]
Hello! Great work! I was wondering if you have done Signature 4 Authentication for API Gateways in this project and if you have, where would that be? Sorry I know this isn't an issue, but if you haven't done it, I think it would be a great idea!

**Comment by davidkretch** [comment]
This is a good issue. I'm not familiar with that; can you paste a link that shows what it should look like, or an example in another language? Paws does use AWS signature version 4 in the background, and we may be able to use that for this as well.
