### ISSUE TITLE
list_objects_v2 should return 'Size' as 'numeric' type

### ISSUE THREAD

**Issue by arunsrinivasan** [paws-r/paws#320]
Hi, when trying to list contents of S3 bucket with large files, `list_objects_v2` returns `NA` because file size in bytes are greater than integer limit (since it's 32-bit in R still).

```r
# All paws.* latest CRAN versions
con$list_objects_v2(Bucket=bucket, delimiter="/", MaxKeys=1L, Prefix="my_dir")
$Contents[[1]]
$Contents[[1]]$Key
[1] "my_dir/file.csv"

$Contents[[1]]$LastModified
[1] "2020-05-18 19:06:00 GMT"

$Contents[[1]]$ETag
[1] "\"8e1ccae713072e54d999a384226905ac-69\""

$Contents[[1]]$Size
[1] NA ### <~~~~ file size is NA

$Contents[[1]]$StorageClass
[1] "STANDARD"

$Contents[[1]]$Owner
$Contents[[1]]$Owner$DisplayName
character(0)

$Contents[[1]]$Owner$ID
character(0)
```

It might need to be converted to `numeric` format.

**Comment by davidkretch** [comment]
Hey, sorry for the delay! The bug fix is now on CRAN. You can get it by installing the latest `paws.common`. Let us know if you have issues. Thank you!
