### ISSUE TITLE
Error in stop(aws_error(request$error)) : bad error message

### ISSUE THREAD

**Issue by BillWeld** [paws-r/paws#329]
The error object contains useful information in its attributes but not in its field values.

Love the library btw.  Super useful!

[tmp.txt](https://github.com/paws-r/paws/files/5250017/tmp.txt)

**Comment by davidkretch** [comment]
Yeah, haha, that is a bad error message. Either I or someone else will try to get to this soon. Thank you for the heads up!

**Comment by davidkretch** [comment]
Hello again, is there an example from another package I can look at where try errors have info in fields? I have been trying and not been able to get it to work -- it seems like `try` puts them in the `condition` attribute.

**Comment by davidkretch** [comment]
Disregard my comment. I understand now.

**Comment by davidkretch** [comment]
Hello again. This should be fixed with the next version of `paws.common` on CRAN in about 2 weeks, due to CRAN rules about how often we can update. Thank you again for the bug report!

**Comment by BillWeld** [comment]
Thanks for a super useful library!

**Comment by davidkretch** [comment]
Sorry for the delay. This is now on CRAN. Let us know if you have any issues! 

Thank you!
