### ISSUE TITLE
AWS Secret Manager get_secret_value

### ISSUE THREAD

**Issue by norquanttech** [paws-r/paws#356]
Hi,

Im retrieving my password from AWS. This works:

# Configure AWS access
svc <- paws::secretsmanager(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = Sys.getenv("AWS_ACCESS_KEY_ID"),
        secret_access_key = Sys.getenv("AWS_SECRET_ACCESS_KEY")
      )
    ),
    region = Sys.getenv("AWS_DEFAULT_REGION")
  )
)
password <- jsonlite::fromJSON(svc$get_secret_value("infront_credentials")$SecretString)$passwordInfront

But ... I was wondering, is there a shorter way to get the value directly? Something like:
password <- svc$get_secret_value("passwordInfront")

**Comment by davidkretch** [comment]
Hey, unfortunately at the moment there is no shortcut.

I don't think we'll be ready to add one for a while. It wouldn't be that much shorter -- it would have to look something like `get_secret("infront_credentials", "passwordInfront")`.

**Comment by norquanttech** [comment]
Ok, no problem. Thanks for your reply.
