### ISSUE TITLE
Update paws sdk to match latest boto3 features

### ISSUE THREAD

**Issue by DyfanJones** [paws-r/paws#357]
Hi all,

I have come across some functionality that boto3 has but paws is missing.

For example sagemaker `create_training_job` (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_training_job):
```python
import boto3 

sm = boto3.client("sagemaker")

sm.create_training_job 
```
```
# arg list:
TrainingJobName
HyperParameters
AlgorithmSpecification
RoleArn
InputDataConfig
OutputDataConfig
ResourceConfig
VpcConfig
StoppingCondition
Tags
EnableNetworkIsolation
EnableInterContainerTrafficEncryption
EnableManagedSpotTraining
DebugHookConfig
DebugRuleConfigurationsBoardOutputConfig
ExperimentConfig
ProfilerConfig
ProfilerRuleConfigurations
```
```r
sm = paws::sagemaker()

sm$create_training_job
```
```
# arg list:
TrainingJobName
HyperParameters
AlgorithmSpecification
RoleArn
InputDataConfig
OutputDataConfig
ResourceConfig
VpcConfig
StoppingCondition
Tags
EnableNetworkIsolation
EnableInterContainerTrafficEncryption
EnableManagedSpotTraining
CheckpointConfig
DebugHookConfig
DebugRuleConfigurations
TensorBoardOutputConfig
ExperimentConfig
```

I am currently updating the R6sagemaker wrapper package to align with python-sagemaker version 2. In the meantime I am happy to add a reminder comment within the R6sagemaker package until paws is updated 😄.

I believe there are a couple more examples, should I add the other examples within this ticket?

**Comment by davidkretch** [comment]
Oh, sorry, we need to update our API definitions. Will do that this weekend. Thanks for the reminder.

**Comment by DyfanJones** [comment]
Thanks @davidkretch for your fast reply. That is great news 😄

**Comment by davidkretch** [comment]
Hey, sorry for the delay. We just updated this on CRAN so these new parameters are now supported. Thank you!

**Comment by DyfanJones** [comment]
Thanks for the fast turn around. I will close this ticket 😄
