### ISSUE TITLE
Are examples for s3$put_object misleading?

### ISSUE THREAD

**Issue by MilesMcBain** [paws-r/paws#362]
The examples in the `put_object` doco imply that a file name is a valid argument for `Body`. But this is not so. In the first example, this will pass the string "HappyFace.jpg" as the file content, creating an invalid jpg file.

These are the examples:
```
svc$put_object(
  Body = "HappyFace.jpg",
  Bucket = "examplebucket",
  Key = "HappyFace.jpg",
  ServerSideEncryption = "AES256",
  StorageClass = "STANDARD_IA"
)

# The following example creates an object. The request also specifies
# optional metadata. If the bucket is versioning enabled, S3 returns
# version ID in response.
svc$put_object(
  Body = "filetoupload",
  Bucket = "examplebucket",
  Key = "exampleobject",
  Metadata = list(
    metadata1 = "value1",
    metadata2 = "value2"
  )
)

# The following example uploads and object. The request specifies optional
# canned ACL (access control list) to all READ access to authenticated
# users. If the bucket is versioning enabled, S3 returns version ID in
# response.
svc$put_object(
  ACL = "authenticated-read",
  Body = "filetoupload",
  Bucket = "examplebucket",
  Key = "exampleobject"
)

# The following example uploads an object to a versioning-enabled bucket.
# The source file is specified using Windows file syntax. S3 returns
# VersionId of the newly created object.
svc$put_object(
  Body = "HappyFace.jpg",
  Bucket = "examplebucket",
  Key = "HappyFace.jpg"
)
}
```
Contrary behavior is demonstrated in the S3 workflow examples: https://github.com/paws-r/paws/blob/main/examples/s3.R#L25-L34 which read the raw file contents and supply that as `Body`.

**Comment by adambanker** [comment]
Thank you for submitting this issue! You are correct, the examples are currently misleading - `put_object` expects the raw file contents for the Body parameter.

Updating that function so that it can accept a file path has been on our to-do list for a while, so I hope to add that feature in soon.

**Comment by adambanker** [comment]
With pr #363 you can now supply a file path for the Body parameter and it will automatically be converted to raw bytes. As a result the first example: 
```r
svc$put_object(
  Body = "HappyFace.jpg",
  Bucket = "examplebucket",
  Key = "HappyFace.jpg",
  ServerSideEncryption = "AES256",
  StorageClass = "STANDARD_IA"
)
```
will work as shown, given that `HappyFace.jpg` is a file at that path.

This update is available now in CRAN.
