### ISSUE TITLE
AWS Personalize endpoints

### ISSUE THREAD

**Issue by buliin** [paws-r/paws#385]
When I try to run following code:

```
svc <- personalize(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = "XXX",
        secret_access_key = "XXX"
      )
    ),
    region = "eu-central-1"
  )
)
svcRt <- personalizeruntime(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = "XXX",
        secret_access_key = "XXX"
      )
    ),
    region = "eu-central-1"
  )
)

svcRt$get_recommendations(campaignArn = svc$list_campaigns()$campaigns[[2]]$campaignArn,
                        userId = "999")
```

The campaignArn is taken from list_campaigns function and it returns correct value.
The get_recommendations function ends with the following error:

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: personalizeruntime.eu-central-1.amazonaws.com
```

On the AWS documentation site: https://docs.aws.amazon.com/general/latest/gr/personalize.html
the endpoint for Personalize Runtime is:
personalize-runtime.eu-central-1.amazonaws.com
not the one from error:
personalizeruntime.eu-central-1.amazonaws.com which comes from this function:
https://github.com/paws-r/paws/blob/main/cran/paws.machine.learning/R/personalizeruntime_service.R

Did AWS change the endpoints? Could you fix it in the function?

EDIT: similar situation for personalize-events endpoints

**Comment by adambanker** [comment]
Thank you for submitting this issue. It appears that Paws is currently using the wrong endpoint prefix for the Personalize Runtime service. We'll work on a fix for that.

In the meantime, you can set a custom endpoint when you declare your service object
```r
svcRt <- personalizeruntime(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = "XXX",
        secret_access_key = "XXX"
      )
    ),
    region = "eu-central-1",
    endpoint = "personalize-runtime.eu-central-1.amazonaws.com"
  )
)
```
with the key line being the endpoint at the bottom. This should alleviate your issue until we submit a proper fix to Paws.

**Comment by davidkretch** [comment]
Hello again. Sorry for the delay. A fix for this is now on CRAN. Please let us know if you have any more issues. Thank you!
