### ISSUE TITLE
Functionality to copy s3 file directly to local disk without table intermediate

### ISSUE THREAD

**Issue by LBragg** [paws-r/paws#401]
Hi. Thanks for the great package. It's very comprehensive. 

I am looking for a function equivalent to boto3's download file (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.download_file) , which can also be done via the AWS cli using 'cp' -- copying a file from an s3 bucket to a local file location.

I may have missed something in the docs, any help would be great. Thanks!

**Comment by adambanker** [comment]
Thanks for submitting this issue! Unfortunately, we do not currently have a function like that. The only way we currently support downloads is by retrieving the content in binary format and then writing that to a file as shown here: https://github.com/paws-r/paws/blob/main/examples/s3.R#L66 .

I agree that it would be nice to create a function that supports this use case, so we will put this on our to-do list.

**Comment by adambanker** [comment]
I added the functionality in #408 but it is not available to use yet - but should be soon. That pull request adds the custom `download_file` function to our sdk generator package - [make.paws](https://github.com/paws-r/paws/tree/main/make.paws). The next time we regenerate the paws packages, that function will be added to [paws.storage](https://github.com/paws-r/paws/tree/main/cran/paws.storage), and therefore available to easily install.

If you would like to use the functionality before then, you can pull the latest version of `main`, and regenerate the packages using the makefile - `make install`. However, we were planning on regenerating the packages this week anyway, so it should be available soon without having to do that.

**Comment by hadley** [comment]
#408 doesn't really solve the problem since the data has to travel through R — an ideal solution would be for libcurl (via curl via httr) to save the data directly to disk. (I have a dim recommendation that this is currently hard/impossible to do correctly in httr, but I'm happy to help resolve that.)

**Comment by adambanker** [comment]
That's a good point. We haven't yet looked into a solution that would bypass R, but that does sound better.

I don't believe we have added an argument to a function that is not an api argument. The closest to that is the wrapper function created in #408. As far as other examples of customizations, there are examples of [custom handlers](https://github.com/paws-r/paws/blob/main/paws.common/R/custom_s3.R) here.

**Comment by hadley** [comment]
@DyfanJones I've already forgotten how httr works, but the chances are it'll be much easier with [httr2](https://github.com/r-lib/httr2)

**Comment by DyfanJones** [comment]
> @DyfanJones I've already forgotten how httr works, but the chances are it'll be much easier with [httr2](https://github.com/r-lib/httr2)

@hadley no worries, from a quick look at `httr`, it should call `curl::curl_fetch_disk` (https://github.com/r-lib/httr/blob/80cb625117629105874d58a234f061b458eefbe6/R/write-function.R#L81-L85) when `httr::write_disk` is pass to `httr::VERB`. 

`httr2` looks really promising :) however I will let the package authors (@davidkretch, @adambanker) make the decision to upgrade from `httr` 😄 .

 I believe this method prevents the data going through R and leaves it to libcurl to do the processing. I will check the unit tests and raise a PR 😄

**Comment by DyfanJones** [comment]
PR (#458) has been merged and will be in the next paws release.

**Comment by DyfanJones** [comment]
Closing this ticket due to paws.storage 0.2.0 has been released to the cran.
