### ISSUE TITLE
s3$list_objects_v2 not working with S3 Access Points

### ISSUE THREAD

**Issue by kamleshgallani** [paws-r/paws#403]
I created an [S3 Acces Point](https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-access-points.html)  to access an S3 bucket. 
While using the paws::s3 list_objects_v2 function, I am unable to perform any operation if I use an access point ARN instead of bucket name.
```
library(paws)
Sys.setenv(
  AWS_PROFILE = "sample-profile",
  AWS_REGION = "us-east-1"
)
s3 <- paws::s3()
s3$list_objects_v2(Bucket = "arn:aws:s3:us-east-1:123456789101:accesspoint/bucket-name")
print(result)
```
It always throws the following error -
`Error: InvalidBucketName (HTTP 400). The specified bucket is not valid.`

I wanted to check if using Access Points is supported with paws for R and if yes, how should I provide the bucket name?

P.S. The equivalent code works with Python boto3 module.
```
import boto3
s3 = boto3.client('s3')
s3.list_objects_v2(Bucket="arn:aws:s3:us-east-1:123456789101:accesspoint/bucket-name")
```

**Comment by davidkretch** [comment]
So unfortunately Paws doesn't support S3 access points. These require special handling and will take some time to add.

It looks like each access point also translates into an endpoint, e.g. 

`arn:aws:s3:us-east-1:123456789101:accesspoint`

becomes

`https://accesspoint-123456789101.s3-accesspoint.us-east-1.amazonaws.com`

So you *might* be able to try using a custom endpoint, like below. However, huge caveat, I haven't tried this yet:

```
s3ap <- paws::s3(config = list(endpoint = "https://accesspoint-123456789101.s3-accesspoint.us-east-1.amazonaws.com"))
s3ap$list_objects_v2(Bucket="bucket-name")
```

I'll try to look figure out a workaround this weekend but probably won't have time to implement an update at the same time.

**Comment by davidkretch** [comment]
Welp, that workaround definitely doesn't work as-is. Sorry, this is more complicated than I anticipated.

**Comment by davidkretch** [comment]
Hello, sorry for the delay! I just submitted a new version of `paws.common` to CRAN (0.3.12). Once it is up in the next few days, you should be able to use S3 access points.
