### ISSUE TITLE
minio as an s3 alternative not working for most operations

### ISSUE THREAD

**Issue by dpastoor** [paws-r/paws#404]
use of minio https://docs.min.io/docs/minio-quickstart-guide.html for testing or local dev is great to emulate s3, but listing/putting of objects doesn't seem to work

```
library(paws)
svc <- s3(config = list(
  credentials = list(
    creds = list(
      access_key_id = "minioadmin",
      secret_access_key = "minioadmin"
    )
  ),
  endpoint = "http://localhost:9000"
))

svc$list_buckets() # works!

## everything below don't work
#bkt <- svc$create_bucket(Bucket =  "test")

svc$list_objects_v2("test")

svc$put_object(
  Body = "example.R",
  Key = "example.R",
  Bucket = "test"
)
```

all will fail with a consistent: 

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: test.localhost
```

It looks like its prepending the bucketname rather than using slash routing?

Any ideas of how to tweak configuration? or generally where to look. I could likely try to help with a PR if pointed where to look a bit (i'm guessing somewhere in the paws.storage) and definitely testing.

**Comment by davidkretch** [comment]
Huh, sorry about that. It looks like it comes from [a custom S3 service handler for prepending the bucket name to the host name](https://github.com/paws-r/paws/blob/df654f9378d4fe0848edb25254b067c813376e9a/paws.common/R/custom_s3.R#L48). I will take a look this weekend. Sorry for the delay.

For background: Each service uses some set of handlers for building and sending API calls. All of those handlers are in the `paws.common` package. S3 uses the so-called [REST-XML handlers](https://github.com/paws-r/paws/blob/main/paws.common/R/handlers_restxml.R), which is shared with some other APIs, but S3 also has its own custom handlers which do things for S3 in particular, including this one.

If you do put together a PR I'd definitely be grateful, but will try to fix soon in any case.

**Comment by davidkretch** [comment]
Sorry for the delay. I've just submitted a fix. It'll probably be a few days before it gets to CRAN.

One unfortunate side effect: you'll have to change the call to `s3(...)` to include a new argument, `s3_force_path_style`:

```r
library(paws)
svc <- s3(config = list(
  credentials = list(
    creds = list(
      access_key_id = "minioadmin",
      secret_access_key = "minioadmin"
    )
  ),
  endpoint = "http://localhost:9000",
  s3_force_path_style = TRUE
))
```

This is due to AWS's planned deprecation of so-called "path-style" S3 URLs: https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

Alternatively, there is an option in MinIO to support the new "virtual hosted" style S3 URLs using the `MINIO_DOMAIN` environment variable. Their documentation is at the bottom of https://docs.min.io/docs/minio-server-configuration-guide.html. If you use this option, you can avoid using the `s3_force_path_style` option in R. Caveat: I have not tried this.

**Comment by dpastoor** [comment]
thanks!

More information here - in following the MINIO_DOMAIN doc a bit, this did _not_ work, but also with the same error. Chasing that actually gave more information. In particular, the resulting curl error is not a paws thing, rather is actually upstream in being unable to resolve the host. Instead it pointed to `/etc/hosts` and the OS needing to understand where to route.

As an experiment, I updated

```diff
⋊> ~/m/d ⨯ cat /etc/hosts                                        
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
+127.0.0.1	data.localhost
```

```
svc <- s3(config = list(
  credentials = list(
    creds = list(
      access_key_id = "minioadmin",
      secret_access_key = "minioadmin"
    )
  ),
  endpoint = "http://localhost:9000"
))

svc$list_buckets() # always worked
svc$list_objects(Bucket = "data") # used to fail, now works!
```

I'm not terribly familiar with the /etc/hosts pattern matching, a quick YOLO test of just *.localhost didn't work, so will investigate there.

As such though, this force path style will be valueable to the average user I think, as modifying that file is a bit heavy and the issue then isn't actually minio, rather the resolution before getting to minio in the first place.

Will continue to update this issue with additional findings...

**Comment by davidkretch** [comment]
Oh, yeah, that makes a lot of sense about the hosts file. Thanks!

I am thinking that maybe we can just tell if someone's using a custom endpoint and not translating the S3 URLs in those cases. I'll try to confirm whether that's what some of the other SDKs are doing. That might also be an easy fix.

**Comment by dpastoor** [comment]
ok - so /etc/hosts cannot do * matching, but in looking around I found the following.

anyone reading use at own risk:

searching lead me to: https://serverfault.com/questions/118378/in-my-etc-hosts-file-on-linux-osx-how-do-i-do-a-wildcard-subdomain

In which I followed the instructions laid out: https://github.com/hubdotcom/marlon-tools/blob/master/tools/dnsproxy/dnsproxy.py




![image](https://user-images.githubusercontent.com/3196313/116818800-36752880-ab3b-11eb-8636-2b8ff140c045.png)


![image](https://user-images.githubusercontent.com/3196313/116818805-39701900-ab3b-11eb-9097-0cfe287f6ce7.png)

![image](https://user-images.githubusercontent.com/3196313/116818813-4260ea80-ab3b-11eb-8ba6-40b223619cfe.png)

```
before and after application shows update SERVER from 10.0.0.2 to 127.0.0.1
⋊> ~/m/m/metworxapi-r on update/api-0.0.4 ⨯ dig test.localhost                                                                                                                                                                                                                                                                              11:35:16

; <<>> DiG 9.10.6 <<>> test.localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15624
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.localhost.			IN	A

;; Query time: 8 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Sun May 02 11:35:20 EDT 2021
;; MSG SIZE  rcvd: 43

⋊> ~/m/m/metworxapi-r on update/api-0.0.4 ⨯ dig test.localhost                                                                                                                                                                                                                                                                              11:35:20

; <<>> DiG 9.10.6 <<>> test.localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59893
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.localhost.			IN	A

;; Query time: 19 msec
;; SERVER: 10.0.0.2#53(10.0.0.2)
;; WHEN: Sun May 02 11:36:07 EDT 2021
;; MSG SIZE  rcvd: 43

⋊> ~/m/m/metworxapi-r on update/api-0.0.4 ⨯ dig test.localhost                                                                                                                                                                                                                                                                              11:36:07

; <<>> DiG 9.10.6 <<>> test.localhost
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28790
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;test.localhost.			IN	A

;; ANSWER SECTION:
test.localhost.		2000	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun May 02 11:36:25 EDT 2021
;; MSG SIZE  rcvd: 48
```

after doing this, I was successfully able to query any type of bucket

```
> svc$list_objects(Bucket = "source")$Contents[[1]]
$Key
[1] "data.csv"

$LastModified
[1] "2021-04-20 10:47:28 GMT"

$ETag
[1] "\"00000000000000000000000000000000-1\""

$Size
[1] 192260063

$StorageClass
[1] "STANDARD"

$Owner
$Owner$DisplayName
[1] "minio"

$Owner$ID
[1] "02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4"
```

It is important to note that I did need to set the `MINIO_DOMAIN=localhost` for this to work so that tip was key, using the vanilla minio without that configuration just returned empty

```
> svc$list_objects(Bucket = "renv")
$IsTruncated
logical(0)

$Marker
character(0)

$NextMarker
character(0)

$Contents
list()

$Name
character(0)

$Prefix
character(0)

$Delimiter
character(0)

$MaxKeys
numeric(0)

$CommonPrefixes
list()

$EncodingType
character(0)
```

**Comment by davidkretch** [comment]
Oh wow, that's cool. Definitely going to extreme lengths!

It does look like it's easy to check for custom endpoints, but I will first check to see what the Python SDK does in this case.

**Comment by davidkretch** [comment]
Alright, cool, I just updated the PR and this should be in soon. Thank you!

**Comment by davidkretch** [comment]
Hey, sorry for the delay. This bug fix is now on CRAN. You can get it by installing the latest version of `paws.common`, 0.3.10, with `install.packages("paws.common")`. Let us know if you have any problems!
