### ISSUE TITLE
SerializationError (HTTP 404) when using get_session_token from sts()

### ISSUE THREAD

**Issue by jtruffa** [paws-r/paws#405]
Hello guys!

I've got 
"`Error: SerializationError (HTTP 404). failed to decode query XML error response`"
when trying to use get_session_token from sts()

opened the service like this:

```
con = sts(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = my_access_key,
        secret_access_key = my_secret_access_key
      ),
      profile = my_profile
    ),
    region = region, 
    endpoint = 'https://dynamodb.us-east-1.amazonaws.com/'
  )
)
```
Then try to get the session token with get_session_token like this:

```
con$get_session_token(
  Duration = 3600L,
  SerialNumber = MFA_serialNumber,
  TokenCode = MFA_code
)
```
I've never used `sts()` nor `get_session_token` before because I have the AWS CLI installed and I'm using that. But would like to standarize my code and implement full paws package.

Thanks in advance!

**Comment by davidkretch** [comment]
Sorry about that. When you are using the AWS CLI, where do you store or retrieve your credentials? Paws should support most of the sources that the CLI does as well.

We also do have a how-to guide for credentials here: https://github.com/paws-r/paws/blob/main/docs/credentials.md. There is an example of using multifactor authentication with the AWS shared configuration file, similar to at least one way that would work in the AWS CLI.

**Comment by davidkretch** [comment]
What is the reason for changing the endpoint? Can you use the default endpoint?

**Comment by davidkretch** [comment]
One alternative that might be open is avoid using STS directly by putting role ARN and serial number in your AWS config file, e.g. something like 

`config`
```
[profile my-profile]
role_arn=arn:aws:iam::123456789012:role/my-role-name
source_profile=my-other-profile
mfa_serial=arn:aws:iam::123456789012:mfa/my-user-name
```

`credentials`
```
[my-other-profile]
aws_access_key_id=foo
aws_secret_access_key=bar
```

**Comment by davidkretch** [comment]
Closing for now. Please let us know if this remains an issue!
