### ISSUE TITLE
R - lexmodelbuildingservice is using `{varName}` in url strings but not replacing it seems

### ISSUE THREAD

**Issue by bschulth** [paws-r/paws#411]
R code seems to be trying to use `{varName}` replacements except that does not do anything on its own.

Perhaps you mean to use the glue::glue operation?
```r
http_path = glue::glue("/bots/{name}/versions")
```
instaed of simply:
```r
http_path = "/bots/{name}/versions"
```

### Browse this search for `xxx/{foo}/yyy` type strings: 
- https://github.com/paws-r/paws/search?q=http_path 

### Specific Examples:

- https://github.com/paws-r/paws/blob/df654f9378d4fe0848edb25254b067c813376e9a/paws/R/lexmodelbuildingservice_operations.R#L104

- https://github.com/paws-r/paws/blob/df654f9378d4fe0848edb25254b067c813376e9a/cran/paws.machine.learning/R/lexmodelbuildingservice_operations.R#L2055

**Comment by davidkretch** [comment]
The string interpolation is actually handled elsewhere. In the case of Lex, in the [REST `rest_build_uri` handler](https://github.com/paws-r/paws/blob/b22d0d72b6e499e0e43212c2f7c3c454d5b51ed9/paws.common/R/handlers_rest.R#L73).

The reasons for this are 1) there is no guarantee that the parameter name, e.g. `name` here, is the same as the string template element name, although in these two cases they are, and 2) the parameter value may need to be encoded in a specific way for the API, e.g. dates may get converted from various R date class objects to strings of a specific format. There is logic to handle those cases.

Are you running into errors that seem to be related to this?

**Comment by davidkretch** [comment]
Hey, sorry for the delay. This bug fix is now on CRAN. You can get it by installing the latest version of `paws.common`, 0.3.10, with `install.packages("paws.common")`. Let us know if you have any problems!
