### ISSUE TITLE
Having difficulty getting credentials running in ECS container.

### ISSUE THREAD

**Issue by summerswallow-whi** [paws-r/paws#414]
First of all let me apologize if I'm just doing something stupid. I'm new to paws and R for that matter. I'm trying to port an inhouse credentialling module from python/boto3 to R. 

Here's what I've done: I set the region then run
```
sm <- paws::secretsmanager()
sm$get_secret_value('my-secret')
```

but I get:

```
Error in f() : No credentials provided
```

According to the documentation on credentials in the section **Get credentials from an EC2 instance or container role** it says paws automatically gets the credential from the container role.. I tried playing around with the config as described in the **
Assume a role with credentials from the environment or an instance/container role** section, but no matter what I put in the `~/.aws/config` file it doesn't seem to change the behavior (unless there is something I'm supposed to do the reload the library (here my ignorance of how R works).

At this point I'm in over my head in troubleshooting and would appreciate any help here.

**Comment by davidkretch** [comment]
Hey sorry about that! You shouldn't need to reload the library -- if the container has an attached role it should attempt to use it automatically. HOWEVER, if you are on an instance that requires [Instance Metadata Service v2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html), Paws does not support that (yet).

If your container has access to the AWS CLI, could you run `system('aws sts get-caller-identity')` within R, or `aws sts get-caller-identity` outside of R to check that it is picking up credentials?

**Comment by summerswallow-whi** [comment]
Thanks for your speedy reply. You may have exposed the issue. that container might have issues accessing the ECS metadata whereas my python container is not. I'd like to keep this issue open while I investigate this angle. If that is the problem and there are not other related problems I'll close the issue. Thanks.

The answer to your question is the python based module is using the IAM roles.

**Comment by davidkretch** [comment]
No problem. Sounds good. Let me know how it goes.

**Comment by summerswallow-whi** [comment]
Not sure the cause but this could be of help to someone else. All the probing of AWS from a shell generated outside rstudio accessed the credentials fine, but from a shell spawned by rstudio did not work. Ultimately, deleting the `.rstudio` directory fixed it. Something must've been configured in there that caused rstudio to block access to the AWS metadata.

Thanks for the assistance.

**Comment by bkbwese** [comment]
Hey @davidkretch, I saw your comment about Instance Metadata V2
> HOWEVER, if you are on an instance that requires Instance Metadata Service v2, Paws does not support that (yet).

Is there an issue tracking this? Is there a timeline for implementing IMDSv2? I'm particularly interested in that feature, and this is the only mention of it that I could find in this project.

**Comment by davidkretch** [comment]
Hello, thanks, that's a good point. I just created an issue here: #441. I unfortunately don't have a timeline. I have a couple other Paws-related things I need to finish first, but I'll take a look this weekend so see how much work it looks like. Sorry about that.
