### ISSUE TITLE
Credential Support Regression in paws.common 0.3.10

### ISSUE THREAD

**Issue by davidski** [paws-r/paws#419]
I'm encountering a reproducible regression in obtaining credentials under paws.common v0.3.10 that does not occur under v0.3.9. I'm struggling to give a clean example with all the redactions required but think I have a useful reprex.

With the config in `~/.aws/config` of:

```bash
[profile REDACT_PROFILE]
region=us-east-2
mfa_serial=arn:aws:iam::REDACTED:mfa/REDACTED
credential_process=aws-vault exec --json REDACTED --prompt=osascript
```

When v0.3.10 of paws.common is installed, the following code block:

```r
Sys.setenv("AWS_PROFILE" = "REDACT_PROFILE")
Sys.setenv("AWS_REGION" = "us-east-2")
s3 <- paws.storage::s3()
s3$list_buckets()
```

Returns `Error in f() : No credentials provided`.

If I pull down v0.3.9 (or earlier) via `renv` the above block pulls the list of available buckets as expected.

Happy to provide more information to help track this one down!

**Comment by davidkretch** [comment]
I have reproduced the bug and will have a fix shortly. Sorry about that :-(

**Comment by davidkretch** [comment]
Hello, an updated paws.common is now on CRAN with a fix to this issue. Sorry about that and thanks for letting us know!

**Comment by davidski** [comment]
Working well for me. Thanks for the quick response and the fix!
