### ISSUE TITLE
Error getting credentials / ECS instance metadata?

### ISSUE THREAD

**Issue by stevecass** [paws-r/paws#429]
Hi, Hope this is the right place to ask this.. 

I have an R script running in a docker image, that connects to SQS using paws. It runs fine locally using AWS_SECRET etc environment variables. When I run it in an ECS container, I see this getting logged when it tries to make an SQS call:

<simpleError in if (metadata_response$status_code != 200) return(NULL): argument is of length zero>
I guess for this to happen metadata_response$status_code must be null for this to happen?

This looks like it's coming from one of the instance metadata http calls inside paws in either get_container_credentials in credential_providers.R or get_instance_metadata in config.R. They both seem to do if (is.null(metadata_response) || metadata_response$status_code != 200) though. Could it be that metadata_response is not null but metadata_response$status_code is null, and the log line is just a bit misleading as the interpreter has expanded the "or" and is logging just the error on the current condition it's checking?

In any case, is there a way I can debug this? I can't see any obvious way to get a stack trace of extra logging from inside the library. Thanks very much.

**Comment by stevecass** [comment]
Just to add, if I pass in the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables via the ECS task definition, paws uses them and connects fine, but I had thought that (after reading https://github.com/paws-r/paws/blob/main/docs/credentials.md) that that shouldn't be necessary as it could get its container credentials. Thanks for any attention you can give this - the package is a real lifesaver so it'd be nice to figure this out. Thanks again.

**Comment by davidkretch** [comment]
Nuts, sorry, you are right -- it should get it automatically. I have been trying to reproduce the error here but not been able to so far. So far I have tried running R inside an ECS Fargate task using the rocker/rstudio Docker image, and inside a SageMaker R notebook, both with attached IAM roles.

I think this might be related to Instance Metadata Service v2 (IMDSv2), which is the new (ca. late 2019) way of getting credentials and I don't think we have added support for it yet unfortunately. Sorry about that. I'll look into it a bit more today.

**Comment by stevecass** [comment]
Yes it's strange. To test I did:

```
locr <- httr::GET(paste0("169.254.170.2", Sys.getenv("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI")))
print(locr)
print(content(locr, "text"))
sqs <- paws::sqs()
msgs <- sqs$receive_message(QueueUrl=sqs_url, MaxNumberOfMessages=10, VisibilityTimeout = 60, WaitTimeSeconds=10)

```
The http response content looks sane (sensitive info removed):

Response [http://169.254.170.2/v2/credentials/redacted]
  Date: 2021-06-14 17:26
  Status: 200
  Content-Type: application/json
  Size: 1.28 kB

{
    "RoleArn": "arn:aws:iam::redacted:role/redacted-ECSTaskRole-redacted",
    "AccessKeyId": "redacted",
    "SecretAccessKey": "redacted",
    "Token": "redacted",
    "Expiration": "2021-06-14T20:57:28Z"
}

But then it logs 
 <simpleError in if (metadata_response$status_code != 200) return(NULL): argument is of length zero>
from the receive_message call

**Comment by davidkretch** [comment]
Thanks for that info. Sorry for the delay. That makes me think the error is coming from somewhere else then. I'm really busy right now but I'll look at it again this weekend.

**Comment by davidkretch** [comment]
Two ideas:
* Will running `traceback()` after the call to `sqs$receive_message` show a traceback?
* If you set environment variable `AWS_EC2_METADATA_DISABLED` to true, e.g. `Sys.setenv(AWS_EC2_METADATA_DISABLED = "true")`, do you get the same error? This option turns off checking for instance metadata, and while I don't believe it should try to call `get_instance_metadata`, it's possible something went wrong trying to get container credentials and it is trying other sources.

**Comment by stevecass** [comment]
Thanks very much for the update. I'll try those and let you know.
