### ISSUE TITLE
HTTP code 400 when trying to access dynamodb tables

### ISSUE THREAD

**Issue by rpodcast** [paws-r/paws#435]
Hello, for some very odd reasons I am unable to successfully list any tables in the dynamo db tables I've created in AWS via `paws`, even though the package works just fine with working with s3 buckets and I am able to list tables using the `awscli` directly. I am running R version 4.0.3 with the latest CRAN releases of the `paws` family of packages. I store the access key and secret in a custom `.Renviron` and here is the code I use to try to connect:

```r
dynamodb <- paws::dynamodb()
# List our DynamoDB tables.
tables <- dynamodb$list_tables()
```

The error I receive is: `Error in curl::curl_fetch_memory(url, handle = handle) : Received HTTP code 400 from proxy after CONNECT`.  Is there any way I can get additional diagnostics to figure out what is happening?  Happy to provide more information in case it helps.

**Comment by davidkretch** [comment]
Well that's not good, sorry about that. Can you paste in the output of `sessionInfo()`?
