### ISSUE TITLE
Malformed XML error running `s3_put_bucket_lifecycle_configuration` examples

### ISSUE THREAD

**Issue by techisdead** [paws-r/paws#438]
Hey,

Header says it all really - I'm trying to use `s3$put_bucket_lifecycle_configuration` to apply a bucket retention policy and I keep getting this XML error.  I'd appreciate any thoughts on this issue, and also recommend considering have it return the xml request body on failure (the xml and json policies are notoriously finicky to get right).

Here's a reprex using the example from the Rdocs.  I've tried multiple variations on this theme and they all fail.

``` r
Sys.setenv(
  AWS_PROFILE = "default",
  AWS_REGION = secret::get_secret("AWS_DEFAULT_REGION") 
  )

s3 <- paws::s3()

s3$create_bucket(Bucket = "reprexlifecycle121",
                 CreateBucketConfiguration = list(
                   LocationConstraint = Sys.getenv("AWS_REGION")
                 ) )

s3$put_bucket_lifecycle_configuration(
  Bucket = "reprexlifecycle121",
  LifecycleConfiguration = list(
    Rules = list(
      list(
        Expiration = list(
          Days = 3650L
        ),
        Filter = list(
          Prefix = "documents/"
        ),
        ID = "TestOnly",
        Status = "Enabled",
        Transitions = list(
          list(
            Days = 365L,
            StorageClass = "GLACIER"
          )
        )
      )
    )
  )
)
#> Error: MalformedXML (HTTP 400). The XML you provided was not well-formed or did not validate against our published schema
```

**Comment by davidkretch** [comment]
Yep, sorry about that! It's a bug in the XML builder which I hope to have submitted to CRAN in the next few days. The XML builder was including extraneous but empty elements, e.g. an empty `NoncurrentVersionTransitions` tag.

With respect to including the request on failure I agree with that idea and will create a new issue for it. It will unfortunately be a while before one of us gets to it though.

**Comment by techisdead** [comment]
That's great news - thanks!

**Comment by davidkretch** [comment]
Hello, sorry for the delay! I just submitted an updated version of `paws.common` (0.3.12) to CRAN and it should be up in the next couple days. Once it's available, you can install `paws.common` and this should work now. I'll leave this open for the time being in case any issues remain.
