### ISSUE TITLE
Support IMDSv2

### ISSUE THREAD

**Issue by davidkretch** [paws-r/paws#441]
See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by achimgaedke** [comment]
DevOps guided by "AWS Foundational Security Best Practices standard" would love to see this:

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-8

I'm considering working around it with reticulate and boto3.

**Comment by DyfanJones** [comment]
Closing this as paws.common 0.5.2 supports this :)
