### ISSUE TITLE
SSO support?

### ISSUE THREAD

**Issue by hadley** [paws-r/paws#457]
Do y'all have plans to support aws sinle sign on? (e.g. https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html)

**Comment by hadley** [comment]
This is the python implementation: https://github.com/boto/botocore/blob/0bf25028b9fa66f030a72daf8499128394e45ba7/botocore/credentials.py#L1990 (via @jspiewak)

**Comment by davidkretch** [comment]
Hey, sorry for the delay. I'll take a look this weekend. This looks like it might be a little more complicated than other credential methods.

**Comment by davidkretch** [comment]
AWS CLI user reference: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html#sso-using-profile
boto3 user reference: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html

**Comment by hadley** [comment]
Thanks!!

**Comment by davidkretch** [comment]
The version of paws.common now on CRAN (0.3.15) now supports SSO using SSO credentials obtained using the AWS CLI, thanks to a pull request by @volkmuth.

You should be able to run e.g. `aws sso login --profile my-profile`, then specify your AWS profile in R, and it will use the credentials saved by SSO.

**Comment by davidkretch** [comment]
I've added documentation for using this here: https://github.com/paws-r/paws/blob/main/docs/credentials.md#use-aws-single-sign-on-sso.

**Comment by DyfanJones** [comment]
Yes you are right @mfogel  this ticket should be closed.
