### ISSUE TITLE
s3 sync in paws?

### ISSUE THREAD

**Issue by jeffbinggeli** [paws-r/paws#461]
Does paws include an S3 operation like sync? I.e., in AWS CLI `aws s3 sync <Localpath> <S3Uri>`

Recommend labeling this as a question. Change to enhancement if appropriate.

**Comment by davidkretch** [comment]
Paws does not have an operation like sync.  It's a bit out of the scope, which is really meant to be limited to direct access to the AWS APIs themselves.  Sorry about that.  :-(
