### ISSUE TITLE
S3 Metadata doesn't work with get_object or head_object

### ISSUE THREAD

**Issue by pashri** [paws-r/paws#467]
To whom it may concern:

I apologise if I'm doing this incorrectly. I've never submitted an issue to anything before.

I've been trying to get the `$LastModified` data for an S3 object, but it's always `NA`, no matter the bucket or key. When I try the same thing in Python with `boto3`, using the exact same credentials and writing the code as similarly as possible, I do get the `LastModified` data.

Here's [basically] how I do it in R with `paws`:

```R
library(paws)

Sys.setenv(AWS_ACCESS_KEY_ID = "********************")
Sys.setenv(AWS_SECRET_ACCESS_KEY = "****************************************")
Sys.setenv(AWS_REGION = "us-east-2")

s3 <- paws::s3()

s3_object <- s3$get_object(Bucket = "this.is.our.bucket", Key = "the/key/to.file")

print(s3_object$LastModified)  # [1] NA
```

and here's how I replicated it in Python with `boto3`:

```python
import os
import boto3

os.environ["AWS_ACCESS_KEY_ID"] = "********************"
os.environ["AWS_SECRET_ACCESS_KEY"] = "****************************************"
os.environ["AWS_REGION"] = "us-east-2"

s3 = boto3.client("s3")

s3_object = client.get_object(Bucket = "this.is.our.bucket", Key = "the/key/to.file")

print(s3_object["LastModified"])  # datetime.datetime(2021, 10, 26, 0, 13, 26, tzinfo=tzutc())
```

_(And obviously, in the real-world scenario, the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` wouldn't be right there in the code)_

The interesting thing is that while this happens with `get_object()` and `head_object()`, but `list_objects()` gets the timestamp. Our temporary solution is to use `list_objects()` and filter on the key.

**Comment by davidkretch** [comment]
Sorry for the delay. Yes, this is a problem. I will be fixing this soon. Thank you for the bug report!
