### ISSUE TITLE
Using Cognito authentication from my AppClient for accessing S3 service

### ISSUE THREAD

**Issue by smartinez-yatiribio** [paws-r/paws#470]
Hi!
I will try to explain my situation here and let me know if something is wrong with my reasoning (I am quite new to AWS world).
In Amazon Cognito, I have a user pool, and each of the users belongs to a group and **each group has an IAM role associated which will determine which S3 resources (files) are able to retrieve**.
Running my Shiny APP,

- I authenticate the user with Cognito, using one App Client (defined in General Settings/App clients), that is, App client id and App client secret defined in Cognito's Amazon section.
- The authentication is successful and the CognitoR package gives me the session_token.
- Then, I want to use the role of the authenticated user to access a file in an S3 bucket which is accessible by the policy of the role of the user. However, when I use the App Client id and secret, using both "paws" or "aws.s3" R packages, I get the same error respectively:
```
Error during wrapup: InvalidAccessKeyId (HTTP 403). The AWS Access Key Id you provided does not exist in our records.
```
or
```
$ Code : chr "InvalidAccessKeyId"
$ Message : chr "The AWS Access Key Id you provided does not exist in our records."
```
Of course, I have an IAM user that is able to access the S3 bucket, but if I don't use the authentication id and key from the authenticated user, I lose the information of what resources in the bucket can access and what others cannot.

Is there something I am missing?
I thought I would be able to use AppClient id and secret for S3 access, but maybe I am wrong...?
Thank you in advance!

**Comment by davidkretch** [comment]
Sorry about that. I am not an expert on this service. Are you working from instructions on how to set this up?

It appears that credentials from Cognito are not AWS credentials, but you can [get temporary AWS credentials using an identity pool](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-scenarios.html#scenario-aws-and-user-pool). Once you have an identity pool it looks like you could use [`get_credentials_for_identity`](https://paws-r.github.io/docs/cognitoidentity/get_credentials_for_identity.html) to get the access key, secret key, and session token.

**Comment by AltayYuzeir** [comment]
Hello, I am now working on a workflow with the same topic, cognitoR and S3 integration. I see this function _get_credentials_for_identity_ is deprecated?
