### ISSUE TITLE
How do I revert to the old version of an object in a versioned S3 bucket?

### ISSUE THREAD

**Issue by wlandau** [paws-r/paws#471]
For https://github.com/wlandau/gittargets/issues/6, I am trying to programmatically revert an object in an S3 bucket to an earlier version. From reading https://docs.aws.amazon.com/AmazonS3/latest/userguide/RestoringPreviousVersions.html, it looks like copying the object to itself (old version to current version) is the most efficient way to go. Is there a way to do that with `paws::s3$copy_object()`? I feel like I am almost there. https://paws-r.github.io/docs/s3/copy_object.html does talk about versioning. I saw:

> By default, x-amz-copy-source identifies the current version of an object to copy. If the current version is a delete marker, Amazon S3 behaves as if the object was deleted. To copy a different version, use the versionId subresource.

Sounds like the right advice, but I do not know how to use headers or metadata. 

I included a reprex. (By the way, does `paws` have functionality for the `aws.s3` functions below?)

``` r
library(paws)
library(uuid)
bucket <- UUIDgenerate()
s3 <- paws::s3()
out <- s3$create_bucket(Bucket = bucket)
aws.s3::put_versioning(bucket, "Enabled")
#> NULL
s3$get_bucket_versioning(bucket)$Status
#> [1] "Enabled"

# old version
out <- s3$put_object(
  Body = charToRaw("old"),
  Bucket = bucket,
  Key = "object"
)
version_old <- aws.s3::get_versions(bucket)$Version$VersionId

# new version
out <- s3$put_object(
  Body = charToRaw("new"),
  Bucket = bucket,
  Key = "object"
)
version_new <- aws.s3::get_versions(bucket)$Version$VersionId

# Should be "new".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object"
  )$Body
)
#> [1] "new"

# Should be "old".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object",
    VersionId = version_old
  )$Body
)
#> [1] "old"

# Should be "new".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object",
    VersionId = version_new
  )$Body
)
#> [1] "new"

# Is this how I revert to the old version?
out <- s3$copy_object(
  Bucket = bucket,
  CopySource = sprintf("/%s/object", bucket),
  Key = "object",
  Metadata = list(`x-amz-copy-source` = version_old)
)
#> Error: InvalidRequest (HTTP 400). This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.
```

<sup>Created on 2021-11-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by davidkretch** [comment]
I found a nearly undocumented method to do this by adding a query parameter to the source key like `/{bucket}/{key}?versionId={version}`, from [here](https://github.com/boto/boto3/issues/403). I believe this is what they mean by "To copy a different version, use the `versionId` subresource". A reprex is below.

An alternative is to delete all subsequent versions using `delete_object(..., VersionId = version_new)`.

There is currently no way to add headers to the HTTP requests before sending them :-/.

With respect to setting bucket versioning with paws, you can do that with `put_bucket_versioning`. You can get the current version of an object from the `put_object` response or from `head_object`, and you can get a list of all versions from `list_object_versions`.

``` r
library(paws)
library(uuid)
bucket <- UUIDgenerate()
s3 <- paws::s3()
out <- s3$create_bucket(Bucket = bucket)
# aws.s3::put_versioning(bucket, "Enabled")
s3$put_bucket_versioning(
  Bucket = bucket,
  VersioningConfiguration = list(
    MFADelete = "Disabled",
    Status = "Enabled"
  )
)
#> list()
s3$get_bucket_versioning(bucket)$Status
#> [1] "Enabled"

# old version
out <- s3$put_object(
  Body = charToRaw("old"),
  Bucket = bucket,
  Key = "object"
)
version_old <- out$VersionId

# new version
out <- s3$put_object(
  Body = charToRaw("new"),
  Bucket = bucket,
  Key = "object"
)
version_new <- out$VersionId

# Should be "new".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object"
  )$Body
)
#> [1] "new"

# Should be "old".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object",
    VersionId = version_old
  )$Body
)
#> [1] "old"

# Should be "new".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object",
    VersionId = version_new
  )$Body
)
#> [1] "new"

# Replace the current version with the old version.
out <- s3$copy_object(
  Bucket = bucket,
  CopySource = sprintf("/%s/object?versionId=%s", bucket, version_old),
  Key = "object"
)

# Should be "old".
rawToChar(
  s3$get_object(
    Bucket = bucket,
    Key = "object"
  )$Body
)
#> [1] "old"

# Alternatively, delete the new version.
# s3$delete_object(
#   Bucket = bucket,
#   Key = "object"
#   VersionId = version_new
# )
```

<sup>Created on 2021-11-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by wlandau** [comment]
Amazing, thank you so much David! Can’t wait to try this out.

**Comment by wlandau** [comment]
Just tested it out and it works for me.

**Comment by wlandau** [comment]
By the way, because of https://github.com/ropensci/targets/issues/711, I am finally switching `targets` from `aws.s3` to `paws`. Much easier to deal with versioned objects and metadata, fewer API calls needed to keep track of object versions, and I feel like I am learning more about AWS because `paws` mirrors the lower-level API so closely.
