### ISSUE TITLE
linux os assumption for sso_credential_process

### ISSUE THREAD

**Issue by yonicd** [paws-r/paws#482]
https://github.com/paws-r/paws/blob/9bf12c3ce55ac10b9f88f428d1b1e41b751b001a/paws.common/R/credential_providers.R#L174

This assumes linux style path for looking up the sso config file, which creates an error in winos.

```r
sso_credential_process(sso_start_url, sso_account_id, sso_region, sso_role_name)
Error: lexical error: invalid char in json text.
                                       ~/.aws/sso/cache/ef83fd07ea6f19
                     (right here) ------^
```

this works 

```r
root <- ifelse(Sys.info()[[1]]=='Windows',Sys.getenv('HOMEPATH'),'~')
sso_cache <- file.path(root, ".aws", "sso", "cache", json_file)
```

**Comment by dpastoor** [comment]
prob could just simplify to calling `normalizePath()` which then would expand out the `~`

if you go down the "custom location based on env", would prob want to use the same env that the aws sdk is going to look which is $HOME or $USERPROFILE - https://docs.aws.amazon.com/sdkref/latest/guide/file-location.html preferentially

**Comment by yonicd** [comment]
normalize path doesnt work always for winos

```r
normalizePath('~')
[1] "C:\\Users\\jonathan.sidi\\OneDrive - Sage Therapeutics\\Documents"

Sys.getenv('HOMEPATH')
[1] "\\Users\\jonathan.sidi"
```

**Comment by dpastoor** [comment]
hmm - interesting - the good ol R funkiness of user home dir default oh windows - does $HOME give back the same as USERPROFILE or the normalizedPath?

**Comment by dpastoor** [comment]
ah I knew I remember this coming up elsewhere - https://github.com/r-lib/gert/issues/35

**Comment by yonicd** [comment]
`HOME` gives back `normalizePath('~')` in winos

**Comment by yonicd** [comment]
I got to HOMEPATH from this [thread](https://superuser.com/a/168719)

**Comment by davidkretch** [comment]
Hello, sorry for the delay.  The fix you submitted is now on CRAN.  You can get it by downloading the latest `paws.common`.  Thank you for the PR!!
