### ISSUE TITLE
assuming roles

### ISSUE THREAD

**Issue by yonicd** [paws-r/paws#488]
Hi Is there a simple way to assume IAM roles through {paws}? I have a shiny app on RSConnect and want to limit the scope of apps to certain roles.

**Comment by davidkretch** [comment]
The most straightforward way is to use the config file to specify a role, and you can see how to do that here: https://github.com/paws-r/paws/blob/main/docs/credentials.md#assume-a-role-with-credentials-from-the-environment-or-an-instancecontainer-role

The less straightforward way is to get the temporary credentials yourself using STS, using some other AWS credentials to start with that are allowed to assume the role. STS will return an access key, secret key, and token for the role, and you can provide that set of credentials to the other service you want to use. We don't have an example of that but you can read about the process here: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html 

And you can see how paws does it here: https://github.com/paws-r/paws/blob/d7b5c577a37ca86ec38dd1329e5f3e07bca7bf3f/paws.common/R/credential_providers.R#L217

**Comment by yonicd** [comment]
thanks for the explanation!
