### ISSUE TITLE
S3 error retries

### ISSUE THREAD

**Issue by TurnaevEvgeny** [paws-r/paws#498]
Hi,
My code looks approximately like that
```r
s3_client <- paws::s3()
body = s3_client$get_object(
                Bucket="my-bucket",
                Key=s3_key)$Body
```
S3 sometimes gives a temporary error like:
```
Error: SlowDown (HTTP 503). Please reduce your request rate
Error: InternalError (HTTP 500). We encountered an internal error. Please try again
Error: ServiceUnavailable (HTTP 503). The service is unavailable. Please retry.
```
What is the correct way to catch and re-try that kind of error with paws?
I've tried 
```r
Sys.setenv(
  AWS_MAX_ATTEMPTS = 15
)
```
I've also tried to provide config similar to python code below but I can't make it work in R.
```
from botocore.config import Config
config = Config(
    retries = dict(
        max_attempts = 10
    )
)
ec2 = boto3.client('ec2', config=config)
```
The errors are rare and it makes it hard to debug. Appreciate any example code to catch and retry.

**Comment by davidkretch** [comment]
Hey sorry about that. Paws doesn't have the ability to automatically retry (long standing issue #406).

You can catch and retry with the following code. You can access the HTTP status code by using `tryCatch(<paws operation>, error = function(e) e)` and looking at the classes of the error, e.g. `http_503`. Hope this helps.

```r
s3 <- paws::s3()
tries <- 0
max_tries <- 3
while (tries < max_tries) {
  resp <- tryCatch(
    s3$get_object(Bucket = "my-bucket", Key = s3_key),
    error = function(e) e
  )
  tries <- tries + 1
  
  # No error: got the object.
  if (!inherits(resp, "error")) {
    break
  }
  # A different error occured.
  else if (!inherits(resp, "http_503")) {
    stop(resp)
  }
  else if (tries == max_tries) {
    stop("max tries reached")
  }
  Sys.sleep(2^tries) # Increase the wait time between each retry.
}
# <... use resp here ...>
```

**Comment by davidkretch** [comment]
Closing. The existing issue to support retries natively will remain open. Please let me know if you had an issue with the example code though!
