### ISSUE TITLE
Question: how to modify the user agent string

### ISSUE THREAD

**Issue by DyfanJones** [paws-r/paws#499]
Just a quick question, is there way to modify the user agent within paws? I am trying to mimic https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/user_agent.py for backend package of my R implementation of sagemaker https://github.com/DyfanJones/sagemaker-r-core. From what I can see user_agent string is created is created here.

https://github.com/paws-r/paws/blob/84e5fc9d8dc05ae40c63f3935bee82256e414a69/paws.common/R/handlers_core.R#L1-L11

And implemented here:
https://github.com/paws-r/paws/blob/df654f9378d4fe0848edb25254b067c813376e9a/paws.common/R/service.R#L16-L52

Many thanks in advanced

**Comment by DyfanJones** [comment]
Not sure if you both are interested in exposing the `user_agent`. But here is a method to allow it to be modified with minimal code changes to existing processes.

```r
metadata_env <- new.env(parent = emptyenv())
metadata_env$user_agent_pattern <- "paws/%s (R%s; %s; %s)"

sdk_version_user_agent_handler <- function(request) {
  paws_version <- utils::packageVersion(methods::getPackageName())
  r_version <- getRversion()
  r_os <- R.Version()$os
  r_arch <- R.Version()$arch
  user_agent <- sprintf(
    metadata_env$user_agent_pattern,
    paws_version, r_version, r_os, r_arch
  )
  request$http_request$header["User-Agent"] <- user_agent
  return(request)
}
```

We could create a helper function to allow users to modify the user agent but in a safe way to prevent `sdk_version_user_agent_handler` function from erroring.

```r
set_user_agent_pattern <- function(pattern = "paws/%s (R%s; %s; %s)"){
  if (lengths(regmatches(pattern, gregexpr("%s", pattern))) != 4){
    stop(
      "pattern must contain 4 '%s' for paws version, R version, operating system and architecture"
    )
  }
  metadata_env$user_agent_pattern <- pattern
}
```
Happy to raise a PR if you both like this feature.

**Comment by davidkretch** [comment]
It feels kinda crazy that they allow users to modify the user agent. It looks like they're taking advantage of "private" fields in the client, e.g. in `client._client_config.user_agent` I think by convention `_client_config` is private. I don't really know the use case, but I feel like if we did want want to allow it, I feel like I'd still want it to be semi hidden, like put it in a variable somewhere in the service object's internal data, e.g. inside your `sagemaker <- paws::sagemaker()` which anyone can overwrite if they know it's there.

**Comment by DyfanJones** [comment]
Happy tp not expose the user agent string and keep it private :) the R sagemaker sdk doesn't have to mimic everything it's python counter part does. Plus I can't see any immediate benefit it gives by exposing the user agent string. For the time being I will close this 😄
