### ISSUE TITLE
s3$put_bucket_lifecycle_configuration is not accepting empty prefix

### ISSUE THREAD

**Issue by y-fischer** [paws-r/paws#510]
I really like the package and use it for my daily work!

But I realized, that it is not possible to put a lifecycle on a bucket with an empty prefix like:
`s3$put_bucket_lifecycle_configuration(Bucket = "testbucket",
                                      LifecycleConfiguration = list(Rules = list(list(ID = "five-days",
                                                                                      Filter = list(Prefix = ""),
                                                                                      Expiration = list(Days = 5),
                                                                                      Status = "Enabled"))))`
Error message:
`Fehler: MalformedXML (HTTP 400). The XML you provided was not well-formed or did not validate against our published schema`

Amazon states (https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html):
> You can specify an empty filter, in which case the rule applies to all objects in the bucket.

How can I put a lifecycle configuration that is affecting all objects in the bucket?
Thanks for any help or improvement!

**Comment by DyfanJones** [comment]
Hi @y-fischer  thanks for raising the issue, it looks like a possibly xml build issue. I will have a look to see if i can get it in the next release 😄

**Comment by y-fischer** [comment]
That would be great! Thanks!

**Comment by DyfanJones** [comment]
This has now been fixed in PR #511. We are getting ready for the next cran release, but in the meantime you can get the dev version through:

```r
remotes::install_github(repo = "paws-r/paws/paws.common/")
```

**Comment by DyfanJones** [comment]
paws.common 0.4.0 is now on the cran and should resolve this issue :)

I will close this ticket for now. If this issue hasn't been resolved for you please feel free to re-open.

**Comment by y-fischer** [comment]
Everything works as expected. Thanks a lot!
