### ISSUE TITLE
sts$assume_role_with_saml(...) returning "No credentials provided"

### ISSUE THREAD

**Issue by bhundt** [paws-r/paws#512]
Hey,

I am trying to assume an AWS role utilising paws with an SAML assertion. Unfortunately when I call
`paws::sts()$assume_role_with_saml(....)` I get the following error message `Error in f(): No Credentiaks provided` (see also attached stack trace).

If I am using the exact same parameter values für my `SAMLAssertion`, `DurationSeconds`, `PrincipialArn` and `RoleArn` and try the same thing using python and the official AWS SDK (boto3) `assume_role_with_saml(...)` works like a charm...

Any idea what I could be doing wrong here?

Thanks!
![stacktrace](https://user-images.githubusercontent.com/97769/180813752-64625983-cf03-427b-85a1-77a9c8792c49.jpg)

**Comment by DyfanJones** [comment]
Ah sorry about that, I believe at the moment paws requires you to put some credentials in. This is similar to: https://github.com/paws-r/paws/issues/489 . In the past I have gotten around this by "fudging" the credentials with some dummy ones for exampel:

```r
sts = paws::sts(config = list(
        credentials = list(
          creds = list(
            access_key_id = "dummy",
            secret_access_key = "dummy"
          )
        )
))
```
This of course isn't ideal. Let me know if the temporary work around works for you. 

For long term goal I will give it some thought in how to implement this without affecting current implementation :)

**Comment by DyfanJones** [comment]
Hi @bhundt I have implement an initial version of how to use anonymous credentials in paws. Please have a go and let me know.

```r
remotes::install_github(repo = "DyfanJones/paws/paws.common/", ref = "anonymous")
```

```r
sts = paws::sts(config = list(credentials = list(anonymous = TRUE)))
```

**Comment by bhundt** [comment]
Both solutions work, thanks @DyfanJones!

**Comment by DyfanJones** [comment]
@bhundt great news. I need to do some extra work around it's implementation with S3, but i am glad it is working for you :)

**Comment by DyfanJones** [comment]
paws.common 0.4.0 is now on the cran and should resolve this issue :)

note: set anonymous credentials as the following :)
```r
sts = paws::sts(config = list(credentials = list(anonymous = TRUE)))
```

**Comment by DyfanJones** [comment]
I will close this ticket for now, please re-open it if there is a repeat issue
