### ISSUE TITLE
`s3` download directly to a file?

### ISSUE THREAD

**Issue by dereckdemezquita** [paws-r/paws#521]
I might have missed something but after consulting the examples on `S3` all I see are methods for requesting something from `S3` and storing the raw response in a variable.

I would like to download things directly to files. I am dealing with very large files and it is not possible for me to store all of this data in memory. I need to have the files downloaded and then I can work on them.

Is there a way to do this?

**Comment by DyfanJones** [comment]
Currently it going to memory than to file. We do have a PR (https://github.com/paws-r/paws/pull/458) that will output directly to disk however I believe there needs to be a few tweaks to it to get it in probably :)

**Comment by dereckdemezquita** [comment]
Okay then thank you very much anywho, nice package. R is the main workhorse for thousands and your work keeps at the edge :)

**Comment by DyfanJones** [comment]
Hi @dereckdemezquita PR (#458) has been merged, and will be in the next paws release

**Comment by DyfanJones** [comment]
Closing this ticket due to paws.storage 0.2.0 has been released to the cran
