### ISSUE TITLE
R package development: How to import selected paws services?

### ISSUE THREAD

**Issue by tomsing1** [paws-r/paws#530]
Thanks a lot for creating this incredibly useful set of packages! I would like to use some of paws' functionality within functions in an R package I am writing. Currently, I import the entire paws namespace, e.g. my NAMESPACE file contains `import(paws)`. 

But I am only using a small subset of paws' functionality - and would like to avoid clashes with imports from other packages (e.g. `paws::glue` clashing with `glue::glue`). What's the recommended way to import individual services from paws? 

E.g. would

```r
importFrom(paws,s3)
importFrom(paws,sts)
```

be the way to access the functionality of the `s3` and `sts` services in my R package?
Many thanks for any advice!

**Comment by DyfanJones** [comment]
Hi @tomsing1, I would recommend you use the paws "category" packages if you only need a subset of functionality from paws. For example:

```r
importFrom paws.storage s3
importFrom paws.security.identity sts
```

**Comment by davidkretch** [comment]
Also, if you’re comfortable with keeping the namespace in your code, you can also avoid importing them at all since most of the functionality doesn’t need to be imported e.g. 

s3 <- paws::s3() # can explicitly use the namespaced function
s3$do_stuff() # doesn’t need to be imported

**Comment by tomsing1** [comment]
That's super helpful! Many thanks for your incredibly quick responses.
