### ISSUE TITLE
CRAN check note: nested <em> in documentation

### ISSUE THREAD

**Issue by davidkretch** [paws-r/paws#531]
From paws.application.integration:
```
checking HTML version of manual ... [6s/12s] NOTE
Found the following HTML validation problems:
swf_register_activity_type.html:154:8: Warning: nested emphasis <em>
```

https://cran.r-project.org/web/checks/check_results_paws.application.integration.html

**Comment by DyfanJones** [comment]
I have started to use unicode decimal `&#42;`. Not sure how to do this programatically however I think it is only 1 case https://github.com/paws-r/paws/pull/670/files. Will tackle this manually for now. I guess 🤔
