### ISSUE TITLE
Clarify that AWS_CREDENTIAL_EXPIRATION is optional when using AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by fh-mthomson** [paws-r/paws#549]
In [this section of `credentials.md` around leveraging environment variables](https://github.com/paws-r/paws/blob/main/docs/credentials.md#set-credentials-for-all-services-with-environment-variables ), it implies that `AWS_CREDENTIAL_EXPIRATION` is required if `AWS_SESSION_TOKEN` is also leveraged:
```
If you have a session token from temporary security credentials, you can set it and its expiration time in environment variables AWS_SESSION_TOKEN and AWS_CREDENTIAL_EXPIRATION:
```

However I've noticed that:
1. I've still been able to successfully authenticate by providing only `AWS_SESSION_TOKEN`
2. The credentials verification process (https://github.com/paws-r/paws/blob/main/paws.common/R/credentials.R#L49-L51) only asserts that, when provided, the value of `AWS_CREDENTIAL_EXPIRATION` is valid.

*Proposal*: Clarify in documentation that `AWS_CREDENTIAL_EXPIRATION` is an _optional_ argument, whereas `AWS_SESSION_TOKEN` is required. *Or*, if there are cases where the former _is_ required, then clarify accordingly.

**Comment by DyfanJones** [comment]
Thanks for raising this @fh-mthomson I will update the documentation :)

**Comment by DyfanJones** [comment]
@fh-mthomson did your PR #559 fix this issue? If so please close this ticket 😄

**Comment by fh-mthomson** [comment]
It did. Thanks, I'll close!
