### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by davidkretch** [paws-r/paws#554]
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpusEWbd/Rbuild15245198a12e5/paws.compute/man/imagebuilder_get_component.Rd:11: unknown macro '\d'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpEbmtVa/Rbuild15407397bc66/paws.management/man/opsworks_update_layer.Rd:36: unknown macro '\A'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpEbmtVa/Rbuild15407397bc66/paws.management/man/opsworks_update_layer.Rd:36: unknown macro '\Z'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpEbmtVa/Rbuild15407397bc66/paws.management/man/ssm_put_parameter.Rd:99: unknown macro '\d'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:40: unknown macro '\d'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:42: unknown macro '\d'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:42: unknown macro '\s'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:44: unknown macro '\s'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:46: unknown macro '\d'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_create_directory.Rd:46: unknown macro '\s'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/directoryservice_start_schema_extension.Rd:23: unknown macro '\n'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role.Rd:85: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role.Rd:85: unknown macro '\u00FF'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role.Rd:86: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role.Rd:86: unknown macro '\u000A'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role.Rd:86: unknown macro '\u000D'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_saml.Rd:71: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_saml.Rd:71: unknown macro '\u00FF'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_saml.Rd:72: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_saml.Rd:72: unknown macro '\u000A'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_saml.Rd:72: unknown macro '\u000D'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_web_identity.Rd:94: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_web_identity.Rd:94: unknown macro '\u00FF'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_web_identity.Rd:95: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_web_identity.Rd:95: unknown macro '\u000A'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_assume_role_with_web_identity.Rd:95: unknown macro '\u000D'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_get_federation_token.Rd:56: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_get_federation_token.Rd:56: unknown macro '\u00FF'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_get_federation_token.Rd:57: unknown macro '\u'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_get_federation_token.Rd:57: unknown macro '\u000A'
Warning: /private/var/folders/y7/hpr91_3s1g993r58n3fsjm580000gn/T/RtmpRPvwMX/Rbuild1552b7e1c0ff7/paws.security.identity/man/sts_get_federation_token.Rd:57: unknown macro '\u000D'

**Comment by DyfanJones** [comment]
Closing this for the time being. If this issue surfaces again lets re-open it :)
