### ISSUE TITLE
Issue Assuming Role on EKS

### ISSUE THREAD

**Issue by andrew-aiken** [paws-r/paws#562]
When using service account annotations the pod can assume the role with a web identity. Running aws cli commands returns the correct role.

## Issue
But when using the raws it will run the commands using the role on the node itself.

## Code
On the service account attached to the pod
```
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/k8s-XXXX-role
```

## Work Around
The entrypoint runs a bash script that has the role assume itself & exports the creds to environment variables that raws can use.

**Comment by DyfanJones** [comment]
Hi @andrew-aiken does pr #559 help to resolve this issue?

**Comment by DyfanJones** [comment]
@andrew-aiken just for update paws.common 0.5.2 has been released on the cran, resolving this issue :)
