### ISSUE TITLE
region error in s3$download_file

### ISSUE THREAD

**Issue by y-fischer** [paws-r/paws#571]
I'm executing the following code (with my profile, endpoint and region, which works correctly with other tools), but with paws I get an error on the region. However, I filled the region correctly, so maybe someone can help if this is a bug or an error on my side.

`s3 <- paws::s3(
    config = list(
      credentials = list(profile = "myprofile"),
      endpoint = "https://myendpoint",
      region = "myregion"))`

`s3$download_file(Bucket = "mybucket",
                 Key = "myfilekey",
                 Filename = "mylocalfilename")`

error message:
`Fehler in get_region(cfgs$credentials$profile) : No region provided`

comment: s3$list_objects and s3$get_object work as expected.

**Comment by DyfanJones** [comment]
Hi @y-fischer sorry about that, it is fairly interesting. I believe it is upset due to the custom function. I will have a look into this. In the meantime you can set your `.aws/config` file to hold you aws region i.e:

```
[default]
region=us-east-1
output=json
```

**Comment by DyfanJones** [comment]
@y-fischer found the issue, it is down to how the current custom method `download_file` has been created. In short it calls the `get_config` function which checks it's parent frame for the config. However, as it has been wrapped, the parent frame doesn't contain a config so it creates a new one and causes this bug. 

There is already a fix for this in paws v-0.2.0 which is currently be worked on. For the time being you can use the work around by setting the config file for aws with the region set.

**Comment by kevinrue** [comment]
+1 
I have the same issue, and only post here to be notified on updated in this thread
Thanks for the great package!

**Comment by y-fischer** [comment]
@DyfanJones somehow the solution with the config is not working for me. I guess I have to wait for paws v-0.2.0. 
Is there a timeline when paws v-0.2.0 will be released?

**Comment by DyfanJones** [comment]
Hi all, sorry about the wait. We have now setup paws on [r-universe](https://paws-r.r-universe.dev/ui#builds) so you should be able to access to all development versions before they are released to the cran. 

To pick up the latest `download_file`  please install paws.storage from r-universe:

```r
# Enable repository from paws-r
options(repos = c(
  pawsr = 'https://paws-r.r-universe.dev',
  CRAN = 'https://cloud.r-project.org')
)

# Download and install paws in R
install.packages('paws.storage')
```

**Comment by DyfanJones** [comment]
Closing this ticket due to paws.storage 0.2.0 has been released to the cran.
