### ISSUE TITLE
feature: s3 generate_presigned_url

### ISSUE THREAD

**Issue by DyfanJones** [paws-r/paws#572]
It would be nice to add in a method to generate a pre-signed url for S3 similar to the python sdk:

```python
import boto3
url = boto3.client('s3').generate_presigned_url(
    ClientMethod='get_object', 
    Params={'Bucket': 'BUCKET_NAME', 'Key': 'OBJECT_KEY'},
    ExpiresIn=3600
)
```

StackOverFlow: https://stackoverflow.com/questions/72355225/s3-aws-generating-presigned-url-in-r

**Comment by DyfanJones** [comment]
paws.storage 0.2.0 has been released to the cran

**Comment by owbezick** [comment]
Hi all, thanks for this feature. I am trying to generate a pre-signed URL; however, I am met with

 <Error>
<Code>InvalidRequest</Code>
<Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
<RequestId>VGDS2GCV99JAA9ED</RequestId>
<HostId>/Iq9V2rLJmvXGYLofe+1uMZz20O/u25GzyTcDQUWExntjB3FUoRrtSL81YMi/aGs9DEMTTwvOdM=</HostId>
</Error>

I can generate a pre-signed URL for this object using the AWS console and my authentication has worked to list buckets and retrieve objects.

Thanks!

**Comment by DyfanJones** [comment]
Hi @owbezick  can you create a separate ticket for this issue? Plus can you provide paws code that caused the issue please.
