### ISSUE TITLE
How to suppress non-applicable data types in the response from dynamodb$query?

### ISSUE THREAD

**Issue by tomsing1** [paws-r/paws#577]
Thanks a lot for providing the R interface to dynamodb. I am learning how to query an existing database right now. But I am a little confused because a query seems to return multiple data types for an attribute. For example, for an attribute of type `S`, the response also returns fields for all of the other possible data types (e.g. `N`, `L`, etc).

Here is a minimal example using the `Music` database that is used throughout the paws documentation:

```r
library(paws)
svc <- dynamodb()

# create the Music table
svc$create_table(
  AttributeDefinitions = list(
    list(
      AttributeName = "Artist",
      AttributeType = "S"
    ),
    list(
      AttributeName = "SongTitle",
      AttributeType = "S"
    )
  ),
  KeySchema = list(
    list(
      AttributeName = "Artist",
      KeyType = "HASH"
    ),
    list(
      AttributeName = "SongTitle",
      KeyType = "RANGE"
    )
  ),
  ProvisionedThroughput = list(
    ReadCapacityUnits = 5L,
    WriteCapacityUnits = 5L
  ),
  TableName = "Music"
)

# add an item
svc$put_item(
  Item = list(
    AlbumTitle = list(
      S = "Somewhat Famous"
    ),
    Artist = list(
      S = "Acme Band"
    ),
    SongTitle = list(
      S = "Happy Day"
    )
  ),
  ReturnConsumedCapacity = "TOTAL",
  TableName = "Music"
)

# query for the item
response <- svc$query(
  ExpressionAttributeValues = list(
    `:v1` = list(
      S = "Acme Band"
    )
  ),
  KeyConditionExpression = "Artist = :v1",
  ProjectionExpression = "SongTitle",
  TableName = "Music"
)
```

Now, when I examine the `Items` element in the response, I see the expected `SongTitle` attribute - but it is a list of all possible data types: 

```
>response$Items[[1]]

$SongTitle
$SongTitle$S
[1] "Happy Day"

$SongTitle$N
character(0)

$SongTitle$B
character(0)

$SongTitle$SS
list()

$SongTitle$NS
list()

$SongTitle$BS
list()

$SongTitle$M
list()

$SongTitle$L
list()

$SongTitle$`NULL`
logical(0)

$SongTitle$BOOL
logical(0)
```

Is my query missing a parameter to suppress the non-applicable data types? Or is this the expected response?
Thank you for any advice!

**Comment by davidkretch** [comment]
This is expected, that is how they designed it. However, the answer to #402 might work for you.

**Comment by tomsing1** [comment]
Perfect! Thanks a lot for pointing me to #402 . That helps a ton.

**Comment by davidkretch** [comment]
Great! Thank you!
