### ISSUE TITLE
Support for SSO sessions (CLI >=2.9)

### ISSUE THREAD

**Issue by MrFlick** [paws-r/paws#583]
It seems that version 2.9.0 CLI introduced SSO sessions. When you run `aws configure sso` and specify an SSO session name, this breaks the `sso_credential_process`. It returns the following error

    Error: Argument object must be of type character or raw vector if serialize is FALSE

that seems to come from paws.common/R/credential_providers.R, specifically

    cache_key <- digest::digest(sso_start_url, algo='sha1', serialize = FALSE)

because `sso_start_url` is NULL. This happens because the format of the config file changed a bit when using the new SSO sessions

The old format was
```
[profile main]
sso_start_url = https://companyname.awsapps.com/start
sso_region = us-east-1
sso_account_id = 100200300400
sso_role_name = AWSRoleName
region = us-east-1
output = json
```
and the new format is
```
[profile main]
sso_session = work
sso_account_id = 100200300400
sso_role_name = AWSRoleName
region = us-east-1
output = json
[sso-session work]
sso_start_url =  https://companyname.awsapps.com/start
sso_region = us-east-1
sso_registration_scopes = sso:account:access
```
For now, you can still specify an blank session name when running `aws configure sso` to generate the old style config file. But going forward it would probably make sense to support the new format.

**Comment by DyfanJones** [comment]
Ah, thanks for letting me know @MrFlick. I will have a play with it to see if I can get a simple solution :) If you have a solution already please feel free to raise a PR or add some suggestions to the ticket 😄

**Comment by MrFlick** [comment]
I don't have a solution prepared. I can kind of guess what's going on based on what I observed, but is there an authoritative source of documentation for the CLI stuff that you used when making this package? My first instinct would be if a key of  sso_session is found, just copy all the values from the corresponding section in the config file into that particular profile.

**Comment by DyfanJones** [comment]
Hi @MrFlick,

I have got a potential solution please give it a try:

```r
remotes::install_github("DyfanJones/paws/paws.common", ref = "sso_v2")
```

Let me know how you get on :)

**Comment by MrFlick** [comment]
@DyfanJones I tested the branch you provided and it worked for my workflow at least. So it seems good to me.

**Comment by DyfanJones** [comment]
paws.common 0.5.5 is now on it's way to the cran. Sorry about the wait on this. I am closing this ticket, please re-open if the problem re-appears
