### ISSUE TITLE
Bad credentials hard to debug

### ISSUE THREAD

**Issue by jonocarroll** [paws-r/paws#599]
Similar to https://github.com/paws-r/paws/issues/512, I've hit the error
```
Error in f() : No credentials provided
```
and struggled to make sense of a) where it came from and b) how to resolve it. I'm using multiple AWS roles and have these configured in `~/.aws/credentials` under the relevant profile tags. I have access to various buckets and files via some of these roles, but there are roles within my org not assigned to me. Following some internal notes, I tried accessing a file with a role similar to - but not one of - mine and hit this error. 
```r
library(paws)

tmp <- tempfile()

Sys.setenv(AWS_PROFILE = "not_my_profile")
s3 <- paws::s3()
s3$download_file("some_bucket", "mtcars.csv", tmp)
# Error in f() : No credentials provided
file.info(tmp)$size
# [1] NA

traceback()
# 13: stop("No credentials provided")
# 12: f()
# 11: call_with_args(provider, credentials)
# 10: get_credentials(signer$credentials)
# 9: sign_with_body(v4, request$http_request, request$body, name, 
#                   region, request$expire_time, request$expire_time > 0, signing_time)
# 8: sign_sdk_request_with_curr_time(request)
# 7: v4_sign_request_handler(request)
# 6: handler$fn(request)
# 5: run(request, sign)
# 4: sign(request)
# 3: send_request(request)
# 2: s3_get_object (...)
# 1: s3$download_file(...)
```
Using a role that does not have access provides some useful feedback
```r
Sys.setenv(AWS_PROFILE = "my-personal-profile")
s3 <- paws::s3()
s3$download_file("some_bucket", "mtcars.csv", tmp)
# Error: AccessDenied (HTTP 403). Access Denied
file.info(tmp)$size
# [1] NA
```
and using the right role, works as expected
```r
Sys.setenv(AWS_PROFILE = "my-valid-profile")
s3 <- paws::s3()
s3$download_file("some_bucket", "mtcars.csv", tmp)
# list()
file.info(tmp)$size
# [1] 1783
```
Is there some way to "validate" the completeness of a credential within the {paws} ecosystem? I am not aware of a way to do this on the AWS side but a few API commands support a `dryrun` / `authdryrun` argument. Simpler would be to confirm that a non-empty set of credentials can be found under the detected `AWS_PROFILE` profile.

**Comment by DyfanJones** [comment]
Hi @jonocarroll, I apologise if I have miss understood anything. Is this asking for a better error message to help debug potential missing credentials i.e.

```r
Sys.setenv(AWS_PROFILE = "not_my_profile")
s3 <- paws::s3()
s3$download_file("some_bucket", "mtcars.csv", tmp)
# Error : Missing credentials from profile `note_my_profile`. Please review you config file....
```
Or if it listed what is missing? Please correct me if I haven't captured it correctly :)

**Comment by jonocarroll** [comment]
I see that `paws.common:::Request()` contains 
```r
        if (is.null(credentials[[aws_profile]])) {
            return(NULL)
        }
```
but this just allows the loop over providers in `paws.common:::get_credentials()` to fall through to `no_credentials()` https://github.com/paws-r/paws/blob/614fc9b90dab8feb7911022964d96a58a11a9d4f/paws.common/R/credentials.R#L5-L19 resulting in the obscure `Error in f()` (since it's a `do.call(f, as.list(data)[args])` operation) and while the call chain does stop there, it's not clear to a user what has gone wrong or why (or where the error comes from). The approach as it is isn't wrong per-se, but a user setting an invalid profile name will have a hard time understanding this error.

I'd like to suggest that in `Request()` (or even earlier in the chain) where `is.null(credentials[[aws_profile]])` and the request is not specifically anonymous, that the error be generated with a meaningful message and traceback, perhaps something like 
```
Error: Profile 'not_my_profile' not found in credentials file
Error in read_credentials(): Profile 'not_my_profile' not found
Error: 'not_my_profile' is not a named profile in `~/.aws/credentials`
```
This is a different error to not setting `AWS_PROFILE` at all, finding the profile but not the associated keys or their values,  and the credentials themselves being insufficient.

**Comment by DyfanJones** [comment]
Ah I see, we could add more information to the logger so a user could get more information. I will have a little look at this over the next few days :)

**Comment by DyfanJones** [comment]
@jonocarroll  Here is an initial implementation for debugging credentials:

```r
remotes::install_github("DyfanJones/paws/paws.common", ref = "cred_logging")
```

``` r
options("paws.log_level" = 3L)
s3 <- paws::s3(list(credentials = list(profile = "dummy")))
s3$list_buckets()
#> INFO [2023-02-22 12:10:52.370]: Profile 'dummy' not found in '/Users/dyfanjones/.aws/credentials'
#> INFO [2023-02-22 12:10:52.381]: Profile 'profile dummy' not found in '/Users/dyfanjones/.aws/config'
#> INFO [2023-02-22 12:10:52.405]: Unable to obtain access_key_id, secret_access_key or session_token
#> INFO [2023-02-22 12:10:52.434]: Unable to obtain iam role
#> Error: No credentials provided
```

<sup>Created on 2023-02-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jonocarroll** [comment]
FWIW, I wasn't aware of the `paws.log_level` option - perhaps I should have looked for that. This is an improvement and using `call. = FALSE` leads to a less obscure message, but in terms of "what does the user do with this info?" I worry that a user who thinks they added credentials (with an invalid profile) still needs more to resolve a fallthrough to "no credentials", keeping in mind that they don't necessarily know that it's a fallthrough.

If intercepting this scenario earlier in the process isn't attractive, could I suggest
```
stop("No compatible credentials provided. Use `options("paws.log_level" = 3L)` for more info")
```
since that nicely provides the actionable information.

**Comment by DyfanJones** [comment]
I see what you mean. If yours aren't aware of logging option then they might struggle setting up there environment.  Made a slight modification to the branch.

```r
remotes::install_github("DyfanJones/paws/paws.common", ref = "cred_logging")
```

Default error message.
```r
s3 <- paws::s3(list(credentials = list(profile = "dummy")))
s3$list_buckets()
#> Error: No compatible credentials provided. Use `options("paws.log_level" = 3L)` for more information.
```

Updated error message after log_level has been set to 3L.
```r
options("paws.log_level" = 3L)
s3 <- paws::s3(list(credentials = list(profile = "dummy")))
s3$list_buckets()
#> INFO [2023-02-23 09:56:41.736]: Profile 'dummy' not found in '/Users/dyfanjones/.aws/credentials'
#> INFO [2023-02-23 09:56:41.749]: Profile 'profile dummy' not found in '/Users/dyfanjones/.aws/config'
#> INFO [2023-02-23 09:56:41.767]: Unable to obtain access_key_id, secret_access_key or session_token
#> INFO [2023-02-23 09:56:43.834]: Unable to obtain iam role
#> Error: No compatible credentials provided.
```

**Comment by jonocarroll** [comment]
I like that; it's actionable and makes it clear what went wrong. Thanks so much!

**Comment by DyfanJones** [comment]
@williazo Thanks for all your help with this. I will push this to the cran next week :) in the mean time it will be accessible through r-universe.

```r
install.packages('paws.common', repos = c('https://paws-r.r-universe.dev', 'https://cloud.r-project.org'))
```

I will keep this ticket open until the cran release 😄

**Comment by DyfanJones** [comment]
paws.common 0.5.6 is on its way to the cran. closing this ticket, thanks for raising this and all the help in implementing it :)
