### ISSUE TITLE
`get_bucket()` is way slower than it should be

### ISSUE THREAD

**Issue by mgirlich** [paws-r/paws#618]
About 90% of the time is spend in `as_list.xml_node()`. Would be nice to speed this up.

<img width="886" alt="image" src="https://github.com/paws-r/paws/assets/18258854/f6ef3d83-1c6e-4d74-becb-9ceaae956534">

**Comment by DyfanJones** [comment]
Hi @mgirlich  you are using another package `aws.s3`. I would suggest you raising this issue with them (https://github.com/cloudyr/aws.s3). I will close this ticket as it isn't related to paws
