### ISSUE TITLE
Submit packages to CRAN

### ISSUE THREAD

**Issue by davidkretch** [paws-r/paws#69]
Check list for CRAN release:
* [ ] devtools::check()
* [ ] devtools::spell_check()
* [ ] devtools::check_rhub()
* [ ] devtools::check_win_devel()
* [ ] devtools::release()

**Comment by davidkretch** [comment]
@adambanker I submitted paws.common to CRAN.

We will have to wait to submit anything else because submissions can rely only on other packages in CRAN, i.e. you can't have a Remotes section in your DESCRIPTION.

**Comment by adambanker** [comment]
@davidkretch that's awesome! We can discuss later what our plan will be for our next phase of submissions, i.e., which packages to submit next.

**Comment by davidkretch** [comment]
Feedback from CRAN:

> Package Information:
> Package: paws.common
> Version: 0.1.0
> Title: Paws Amazon Web Services API Package Common Functions

Please omit the redundant "Package Comon Functions".



> Author(s): David Kretch [aut, cre], Adam Banker [aut], Amazon.com, Inc.
>    [cph]
> Maintainer: David Kretch <david.kretch@gmail.com>
> Suggests: covr, testthat
> Description: Common functions for the Paws Amazon Web Services API
>    packages.

Please explain ehat that is, e.g. by adding some web reference in the 
form <https.....>.

We see

* checking examples ... NONE

We understand it is not simple to execute the functions, hence you can 
wrap them in \dontrun{}, but it is nice for the users  to explain how 
the fucntions are supposed to be called.

Please fix and resubmit.

**Comment by davidkretch** [comment]
@adambanker I resubmitted the package to CRAN.

**Comment by davidkretch** [comment]
paws.common is now on CRAN: [https://cran.r-project.org/package=paws.common]

**Comment by davidkretch** [comment]
R CMD check output for package generated by the `bug/make_paws_fixes` branch on the first 100 APIs.
[00check.log](https://github.com/paws-r/paws/files/2973016/00check.log)

Summary:
* [ ] LaTeX warnings:
```
prepare_Rd: directoryservice_start_schema_extension.Rd:19: unknown macro '\n'
prepare_Rd: iam_change_password.Rd:17: unknown macro '\u'
```
* [ ] Rd line widths too long.
```
  \usage lines wider than 90 characters:
       applicationdiscoveryservice_associate_configuration_items_to_application(applicationConfigurationId,
  \examples lines wider than 100 characters:
       arn = "arn:aws:devicefarm:us-west-2:123456789101:run:5e01a8c7-c861-4c0a-b1d5-5ec6e6c6dd23/0fcac17b-6122-44d7-ae5a-12345EXAMPLE"
```
* [ ] `decode_xml` used by `s3_customizations.R` does not exist outside `paws.common`.

Other issues outside R CMD check
* [ ] The service descriptions in <foo>_service.R are truncated.

**Comment by davidkretch** [comment]
Submitted paws.common 0.1.1 to CRAN.

**Comment by davidkretch** [comment]
Submitted paws to CRAN.

**Comment by davidkretch** [comment]
Resubmitted after fixing broken links.

**Comment by davidkretch** [comment]
Cannot submit full Paws package -- too big. Will submit individual packages and a collector package.

Submitted paws.ec2 to start with.

**Comment by davidkretch** [comment]
Published.
