### ISSUE TITLE
Basic list_objects broken with IAM credentials 

### ISSUE THREAD

**Issue by gp-dev-pw** [paws-r/paws#698]
With paws 0.3, the following set of commands would list the content of my bucket as expected
```
library(paws)
svc <- paws:s3()
svc$list_objects(Bucket = "my_bucket")
```
With 0.4.0, if I do the following
```
library(paws)
svc <- paws:s3(region="us-east-1)
svc$list_objects(Bucket = "my_bucket")
```
I receive the following error message
```
Error in as.POSIXct.default(NULL) :
do not know how to convert 'NULL' to class "POSIXct"
```
I have the same error if I try with `list_objects_v2`

**Comment by DyfanJones** [comment]
Hi @gp-dev-pw , what version of R do you have?

**Comment by DyfanJones** [comment]
Found this issue, with older versions of R  there is no method for NULL within `as.POSIXct`. Please try devel version and let me know if this fixes your issue

```r
remotes::install_github("DyfanJones/paws/paws.common", ref = "old_r_posixct")
```

**Comment by gp-dev-pw** [comment]
Yes. It does fix the issue and the `list_objects` function. Thank you.

**Comment by DyfanJones** [comment]
Closing this ticket as paws.common 0.6.3 has been released to the cran.
