### ISSUE TITLE
unable to retrieve IAM credentials in sagemaker serverless inference

### ISSUE THREAD

**Issue by ncullen93** [paws-r/paws#737]
I am unfortunately having an issue on sagemaker inference, but only on the serverless inference. I am deploying a model using the standard vetiver functions for doing so (ref: https://juliasilge.com/blog/vetiver-sagemaker/), along with some slight changes to the config to be serverless. The vetiver deployment works perfectly with real-time inference but when I change to serverless, it fails because paws can't find any credentials.

I wonder if there is anything special that should be done when building a docker for serverless inference, or if this is just a paws issue. Thanks! Apologies for double posting.

**Comment by DyfanJones** [comment]
Hi @ncullen93 sorry to here that. Is it possible for you to include an example in what you did? I would like to reproduce :)

**Comment by DyfanJones** [comment]
Thanks for the example code :) I will have a little look at it to see why it is failing :)

**Comment by DyfanJones** [comment]
@ncullen93 nearly forgot do you have any logs or errors?

**Comment by DyfanJones** [comment]
@ncullen93 no worries I will have a look now :)

**Comment by DyfanJones** [comment]
@ncullen93 do you get a successful endpoint build? and this error only happens when attempting predict?

**Comment by DyfanJones** [comment]
Interesting I am getting the following error:

![image](https://github.com/paws-r/paws/assets/23235152/454eb433-d073-4d24-b997-01d3f69ae760)

I am going to try with the latest dev version of paws.common

**Comment by ncullen93** [comment]
Interesting.. seems related to the credentials. I wonder if there is something that must be changed in the docker file. Hard to find any documentation on the difference between real-time and serverless inference from a model perspective.

**Comment by ncullen93** [comment]
> @ncullen93 do you get a successful endpoint build? and this error only happens when attempting predict?

No, the endpoint build fails. At the very end just like yours.

**Comment by DyfanJones** [comment]
Hmm I wonder if it is down to paws only looking at the ipv4 for iam credentials and we need to include the support for ipv6 🤔

**Comment by DyfanJones** [comment]
Found it, we need to support this environmental variable:

`AWS_CONTAINER_CREDENTIALS_FULL_URI`

This will then get the credentials :D I will have a look in implementing this shortly :D

**Comment by ncullen93** [comment]
That sounds promising! Happy to test it whenever.. appreciate the help immensely.

**Comment by DyfanJones** [comment]
@ncullen93 I believe I have a solution. Please try out:

```r
remotes::install_github("dyfanjones/paws/paws.common", ref = "env_container_cred_full_uri")
```

And let me know how you get on :)

**Comment by ncullen93** [comment]
It works! You are an absolute mad lad. 

A little trouble making predictions from the endpoint using `paws.machine.learning::sagemakerruntime` however. It's giving a 424 model error and the log on aws says the data is empty. So the input data is not getting picked up somehow. This is the code used to invoke an endpoint:

```R
predict.vetiver_endpoint_sagemaker <- function(object, new_data, ...) {
    check_installed(c("jsonlite", "smdocker", "paws.machine.learning"))
    data_json <- jsonlite::toJSON(new_data, na = "string")
    config <- smdocker::smdocker_config()
    sm_runtime <- paws.machine.learning::sagemakerruntime(config)
    tryCatch(
        {
            resp <- sm_runtime$invoke_endpoint(object$model_endpoint, data_json, ...)
            resp <- resp$Body
        },
        error = function(error) {
            error_code <- error$error_response$ErrorCode
            if (!is.null(error_code) && error_code == "NO_SUCH_ENDPOINT") {
                cli::cli_abort("Model endpoint {.val {object$model_endpoint}} not found.")
            }
            stop(error)
        }
    )
    con <- rawConnection(resp)
    on.exit(close(con))
    resp <- jsonlite::fromJSON(con)
    return(tibble::as_tibble(resp))
}
```

Still, I know the endpoint works because invoking it from python returns predictions. You can see there is a slight addition to the recommended way to invoke a serverless SM endpoint compared with real-time so perhaps that's the issue ? 

```Python
response = runtime.invoke_endpoint(
    EndpointName=endpoint_name,
    ContentType=content_type, # this is added for serverless: e.g., "application/json"
    Body=payload
)
```

In any case, I will invoke the endpoints from python anyways so not a big deal I think. Really appreciate the help.

**Comment by DyfanJones** [comment]
That is great news :)  I can get this into the latest paws.common 0.7.0 release (#720)


Does adding ContentType work from paws? When invoking the endpoint as well?

Possibly work raising a pr on vetiver to get the serverless method enabled. @juliasilge would vetiver be interested in extending its sagemaker support with serverless stuff? I am more than happy to contribute again :)

**Comment by DyfanJones** [comment]
@ncullen93 you could also try sending the data across as a raw vector, so:

```r
data_json <- charToRaw(jsonlite::toJSON(new_data, na = "string"))
```

Let me know how you get on :)

**Comment by ncullen93** [comment]
I will try it. I think that should work.

**Comment by DyfanJones** [comment]
@ncullen93 Just had a little play and the following worked for me:


```r
predict(new_endpoint, ames_test, ContentType = "application/json")
```

This is using the standard `vetiver:::predict.vetiver_endpoint_sagemaker` method.

**Comment by DyfanJones** [comment]
Note: paws.common 0.7.0 has been released to the cran

**Comment by juliasilge** [comment]
Thank you so much for your continued support on this @DyfanJones!

Do you think I should set `ContentType = "application/json"` in the predict method for a SageMaker endpoint?
https://github.com/rstudio/vetiver-r/blob/581a4e98d9673013a386a9715f180f025fc3f03f/R/sagemaker.R#L417
I am thinking yes, since we are definitely passing JSON?

**Comment by DyfanJones** [comment]
Yeah I agree. If anything we could have it in the parameters for the predict method:

```r
predict.vetiver_endpoint_sagemaker <- function(object, new_data, content_type = "application/json", ...) { }
```
