### ISSUE TITLE
Connection to localstack

### ISSUE THREAD

**Issue by rabalasubramani3** [paws-r/paws#747]
Will this package work with localstack. How do I connect to localstack. Any help appreciated?

**Comment by DyfanJones** [comment]
Hi @rabalasubramani3 I am not familiar with local stack. Do you have an example for how another sdk works with it (if possible boto3)? I can then use that as a template to address the issue 😁

**Comment by DyfanJones** [comment]
It looks like you only need to change the endpoint (correct me if I am wrong). So it should work similar to how we can connect to minio s3.

**Comment by DyfanJones** [comment]
I will see if I can get it spun up on my local computer and update the ticket accordingly :)

**Comment by rabalasubramani3** [comment]
I tried various versions of these..

 s3 <- paws::s3(
     config = list(
         credentials = list(
             creds = list(
                 access_key_id = "foo",
                 secret_access_key = "bar"
             )
         ),
         endpoint='http://s3.localhost.localstack.cloud:4566',
         region='us-east-1'
    
Here is my localstack docker-compose.yml

  localstack:
      image: localstack/localstack:2.0.0
      container_name: sagpro_localstack 
      environment:
        - AWS_DEFAULT_REGION=us-east-1
        - DOCKER_HOST=unix:///var/run/docker.sock
        - AWS_ACCESS_KEY_ID=foo
        - AWS_SECRET_ACCESS_KEY=bar        
      ports:
        - "127.0.0.1:4566:4566"            # LocalStack Gateway
        - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      volumes:
        - sagpro_localstack_volume:/var/lib/localstack
        - /var/run/docker.sock:/var/run/docker.sock    
      networks:
        - sagpro-net

**Comment by rabalasubramani3** [comment]
> Hi @rabalasubramani3 I am not familiar with local stack. Do you have an example for how another sdk works with it (if possible boto3)? I can then use that as a template to address the issue 😁

localstack allows you to mimic AWS setup locally.

https://www.localstack.cloud/

**Comment by rabalasubramani3** [comment]
s3 <- paws::s3(
  config = list(
    credentials = list(
      creds = list(
        access_key_id = "foo",
        secret_access_key = "bar"
      )
    ),
    endpoint='http://localstack:4566',
    region='us-east-1'
  )
)

within "sagpro_localstack" R-studio and localstack all sitting in same network.

**Comment by DyfanJones** [comment]
For completeness you can set all your login details in the aws configs. So for example:

`.aws/credentials` 
```
[localstack]
aws_access_key_id=youraccesskey
aws_secret_access_key=yoursecretkey
```

`.aws/config`
```
[profile localstack]
region=us-east-1
output=json
services = localstack

[services localstack]
s3 = 
 endpoint_url = http://localstack:4566/
```


```r
library(paws)

client <- s3(config(credentials(profile ="localstack")))
```

**Comment by DyfanJones** [comment]
Closing this ticket
